### ISSUE TITLE
Language Bindings

### ISSUE THREAD

**Issue by TylerBrinkley** [EncompassRest/EncompassRest#1]
As was discussed in the SDK to API Experience session it looks like Ellie Mae will be providing Language Bindings to .NET and others. Do you know if that will address the same problems as this library does?

**Comment by hfcjweinstock** [comment]
What are you specifically talking about when you say language bindings?  EM may have sample snippets of code, but no fully fleshed out interface project with extended features.

**Comment by scottsauber** [comment]
I think no one knows what EM is going to provide at this point.  I heard conflicting answers from different EM team members at Experience.  In the developer lab - I asked (before I had seen the session where this project was mentioned) and they said there would be **no** POCO's provided or wrappers of any kind, they would just provide "sample reference apps."  In another session (what @TylerBrinkley is referring to, I think) they mentioned they would provide language bindings for .NET, Java, and NodeJS.  If that is the case, it would seem like this project would overlap with that goal.

This is just a gut feel thing, but I feel like EM is at least a year out from providing these language bindings and it isn't a top priority for them.  They have all the REST API's to ship, NG, and a whole host of other stuff.

**Comment by hfcjweinstock** [comment]
ah, ok.  So the word from Cheung to me was, there would be no full POCO's.  Ellie would provide sample code snippets for using the API's.  In the c# environment, he supports the community effort to build something.

**Comment by scottsauber** [comment]
They were a little inconsistent with their messaging overall, I would say.  Besides the language bindings thing, it was mentioned in a session that we needed to get with our account rep to be REST API enabled, but we actually don't.  Just sign up and it works (at least for me).

I think this is just the growing pains of being early adopters.

**Comment by hfcjweinstock** [comment]
when you say "it works" are you referring to the "ty it now"?  because that is not tied to your system.  that is a test environment.  when you try to use the API outside of the try it now, it will need your client id and client secret which is something you need to get from your AE.

**Comment by scottsauber** [comment]
Sorry - my wording was ambiguous.  I just meant signing up for the Developer Portal in general.  In one of the early REST API classes they said we'd have to go through our account rep before signing up, then someone in the class said they just clicked the sign up button, and it let them in which surprised the speaker.  He then said go ahead and sign up.

**Comment by TommyWats** [comment]
Hey Scott, I just tried and got in on a whim. Here is what I did:
1.) go to https://idp.elliemae.com/devconnect/index.html 
2.) click get started
3.) fill out the form
4.) enter your instance BExxxx or TEBExxxx
5.) If it worked, you will get an automated email asking to verify your email account.

**Comment by hfcjweinstock** [comment]
The inconsistency deals with getting the clientID/clientSecret for using the API.  They are working on securing it better so that not anyone in the organization could access it.

**Comment by TylerBrinkley** [comment]
@hfcjweinstock Seeing how Ellie Mae is unlikely to provide these language bindings anytime soon I would like to start contributing to this project.

**Comment by TylerBrinkley** [comment]
Well, Ellie Mae released their .NET bindings this weekend at https://github.com/EllieMae/developerconnect-dotnet-bindings. It looks like it's just a swagger generated client library. Still need to comb through it to see if there are any ideas there that we could use here.

**Comment by hfcjweinstock** [comment]
there are a few command reference things we can use to learn how to send the command correctly, other than that, our implementation is far superior.

**Comment by TylerBrinkley** [comment]
What command references are you talking about?

**Comment by hfcjweinstock** [comment]
the undocumented method for creating a loan with a template.

**Comment by TylerBrinkley** [comment]
Yeah, you're right. It will be useful for undocumented features.

**Comment by TylerBrinkley** [comment]
My original concerns that this library might become obsolete and a wasted effort with Ellie Mae's .NET Bindings has turned out to be completely unfounded. As Jesse said, EncompassRest is far superior and will be way more convenient to work with. Of course everyone is free to use the library they prefer but I think most will come to the same conclusion.

**Comment by TylerBrinkley** [comment]
Since Ellie Mae's .NET Bindings have been released I'm closing the issue. Feel free to continue discussing the two libraries.

**Comment by scottsauber** [comment]
> My original concerns that this library might become obsolete and a wasted effort with Ellie Mae's .NET Bindings has turned out to be completely unfounded. As Jesse said, EncompassRest is far superior and will be way more convenient to work with. Of course everyone is free to use the library they prefer but I think most will come to the same conclusion.

I haven't dug into this library or the "official" Ellie Mae one yet.  so I'm curious what makes you say that this one is far superior?  More features?  Better API?  Perf? Something else?

**Comment by hfcjweinstock** [comment]
We are accounting for many of the errors and bug in the API at the moment, as well as a cleaner serialization routine for loan files.  We track changed values so you can pull a loan, change 1 thing and patch it back to ellie mae and only that field is serialized. Makes for smaller and more efficient payloads. Ours also reuses the HTTP Client across the connection so there is not a new client object for every call.  And we have an auto reconnect for an expired token.  Among a few enhanced features.

Jesse Weinstock
Development Manager
Homestead Funding Corp (NMLS 3232)
8 Airline Drive
Albany, NY 12205
Office: (518) 464-1100 Ext. 707
Direct: 518-292-1640


[cid:image001.png@01D18FFC.85A1A970]<https://homesteadfunding.com/>[cid:image002.png@01D18FFC.85A1A970]<https://www.facebook.com/HomesteadFundingCorp> [cid:image003.png@01D18FFC.85A1A970] <https://twitter.com/homesteadcorp>  [cid:image004.png@01D18FFC.85A1A970] <https://www.linkedin.com/company/homestead-funding-corp>  [cid:image005.png@01D18FFC.85A1A970] <https://www.youtube.com/user/HomesteadFundingCorp>
[cid:image006.jpg@01D18FFC.85A1A970]<http://www.homesteadfunding.com/>

**Comment by TylerBrinkley** [comment]
More features?
Definitely
* Dirty checking serialization
* Option to auto retrieve new token and resend the request when using an expired token
* Raw API calls support
* Ability to assign and retrieve string properties as enum values to reduce the need to use magic strings
* .NET Standard support
* Extension data support, for when Ellie Mae adds properties to the returned json objects but the library isn't updated yet
* `CancellationToken` support
* Properties are lazily created upon gets so you don't need to new them up first to use them

Better API?
Absolutely
* Way more convenient interface with a single defined entry point, the `EncompassRestClient` object which is the equivalent of the `Session` object in the SDK
* Types are better named, e.g. `Loan` instead of `LoanContract`
* One library package to install
* Publicly exposes only relevant .NET API
* Uses decimal instead of double to prevent precision loss

Perf?
Likely
I haven't done any performance tests between the two libraries but `EncompassRest` should perform much better. Here are a few reasons why.
* Serializes directly to output `Stream` meaning no string allocation
* Reuses one `JsonSerializer` instance so it's cache isn't needed to be repopulated on each request
* `HttpClient` is in general more performant over `RestSharp`

Something else?
Probably

**Comment by scottsauber** [comment]
Cool - thanks guys.  I would recommend throwing that list on the readme, because I imagine many will have the same question as me.
