### ISSUE TITLE
Add option to avoid EncompassRest from storing user credentials

### ISSUE THREAD

**Issue by TylerBrinkley** [EncompassRest/EncompassRest#105]
With the following proposed API addition we would no longer be required to store user credentials for users that want to retrieve a new token when one expires. Also, it would allow users to know and act when they try to use an expired token.

## Proposed API
```diff
 namespace EncompassRest {
     public class EncompassRestClient {
+        public static Task<EncompassRestClient> CreateAsync(string apiClientId, string apiClientSecret, Func<TokenCreator, Task<string>> tokenInitializer);
     }
 }
 namespace EncompassRest.Token {
+    public sealed class TokenCreator {
+        public Task<string> FromUserCredentialsAsync(string userId, string password, CancellationToken cancellationToken = default);
+        public Task<string> FromAuthorizationCodeAsync(string redirectUri, string authorizationCode, CancellationToken cancellationToken = default);
+    }
 }
```

## Example Usage
```c#
using (var client = EncompassRestClient.CreateAsync("apiClientId", "apiClientSecret",
    tokenCreator => tokenCreator.FromUserCredentialsAsync("userId", "password")))
{
    // use client
}
```

Thoughts?

**Comment by hfcjweinstock** [comment]
how would the user handle the expired token automatic reauth?

**Comment by TylerBrinkley** [comment]
We would just invoke the stored `Func<TokenInitializer, Task>` when the token being used is expired, which would then re-initialize the client with a new token. Then we'd resend the last request. We would need to implement double checked locking to prevent the method from being called multiple times for the multi-threaded case.

**Comment by hfcjweinstock** [comment]
ok....then should `TokenInitializer` be sealed or should we allow for custom initializers?

**Comment by TylerBrinkley** [comment]
Yes, it should be sealed. `TokenInitializer` is just the class to use to initialize an access token to the client object. Since it's a `Func` the user can easily customize how they initialize it so long as they use the methods on `TokenInitializer`.

So for example, a user could create a `Func` that makes a `SignalR` request to an Encompass NG browser to retrieve a new token with the NG javascript utilities and then re-initialize the client with that access token by calling the `TokenInitializer.FromAccessToken` method.

**Comment by TylerBrinkley** [comment]
I just updated the proposal so that it provides a `TokenCreator` parameter instead of `TokenInitializer` to prevent allowing users from re-initializing the token at any time.
