### ISSUE TITLE
{"error_description":"Invalid username & password combination.","error":"invalid_grant"}

### ISSUE THREAD

**Issue by amadard** [EncompassRest/EncompassRest#108]
I may be missing something obvious, but I am running into this error when trying to create a RestClient for a non-Super Admin user.

I just changed the user's password in the settings.  I confirmed the password and username are correct, I can log into the SmartClient using them.  However, my restclient keeps throwing this error:

{"error_description":"Invalid username & password combination.","error":"invalid_grant"}

Is there a setting in Developer Connect I need to change to allow non-SuperAdmins access to the APIs?

**Comment by TylerBrinkley** [comment]
I don't believe so. Please try it in Postman and see if you get the same, if so then I'd recommend creating a support ticket.

**Comment by amadard** [comment]
Not working.  Submitted a case.

Thanks!

**Comment by amadard** [comment]
It was the Persona Settings - Access - Both Microsoft Windows Encompass Client and Encompass Mobile (LO Connect) in a web browser

Didn't have it checked in Encompass for those user's personas.

**Comment by TylerBrinkley** [comment]
Thanks for the update. Hopefully that will help others experiencing this.
