### ISSUE TITLE
API Design Decisions

### ISSUE THREAD

**Issue by TylerBrinkley** [EncompassRest/EncompassRest#11]
I was hoping we could flesh out the API design.

1. I think `Session` might be better renamed to `EncompassRestClient` or `EncompassApiClient` as those better match what they are. I know `Session` was used in the SDK but I don't think that really applies here.
2. Initialization of what's currently named as a `Session` should be done through factory methods to enable async construction as there is no such thing as an async constructor. Additionally, this will make it more clear in how you're constructing the `Session` through the name of the factory method.
3. Currently the only way to create a `Session` is with user credentials. I think it's necessary that you are able to create a `Session` also using the `Authorization Code` flow as well as when you already have an `Access Token`.
4. Also I think the project name and namespace should become `EncompassRest` per [Microsoft's capitalization conventions](https://msdn.microsoft.com/en-us/library/ms229043(v=vs.110).aspx).

Below is the base public API I envision for this library.

```csharp
namespace EncompassRest {
    public sealed class EncompassRestClient : IDisposable { // Not publically constructible
        public static Task<EncompassRestClient> CreateFromUserCredentialsAsync(string clientId, string clientSecret, string instanceId, string userId, string password, TokenExpirationHandling tokenExpirationHandling = TokenExpirationHandling.Default);
        public static Task<EncompassRestClient> CreateFromAuthorizationCodeAsync(string clientId, string clientSecret, string redirectUri, string authorizationCode);
        public static EncompassRestClient CreateFromAccessToken(string clientId, string clientSecret, string accessToken, string tokenType = "Bearer");

        public Token.AccessToken AccessToken { get; }
        public TokenExpirationHandling TokenExpirationHandling { get; }
        // + getter properties to the various subsystems, e.g. BatchUpdate, Loans, Pipeline

        public void Dispose();
    }
    public enum TokenExpirationHandling {
        Default,
        RetrieveNewToken
    }
}
namespace EncompassRest.Token {
    public sealed class AccessToken { // Not publically constructible
        public EncompassRestClient Client { get; }
        public string Token { get; }
        public string Type { get; }

        public Task<TokenIntrospectionResponse> IntrospectAsync();
        public Task<bool> RevokeAsync();
        public override string ToString();
    }
    public sealed class TokenIntrospectionResponse {
        public TokenIntrospectionResponse();

        public bool Active { get; set; }
        public string Scope { get; set; }
        public string ClientId { get; set; }
        public string UserName { get; set; }
        public string TokenType { get; set; }
        public DateTime Expiration { get; set; }
        public string Subject { get; set; }
        public string EncompassInstanceId { get; set; }
        public string UserId { get; set; }
        public string UserKey { get; set; }
        public string EncompassUser { get; set; }
        public string IdentityType { get; set; }
        public string EncompassClientId { get; set; }
        public string RealmName { get; set; }
    }
}
```

**Comment by hfcjweinstock** [comment]
interesting.  I like the layout.  One thing to keep in mind is token timeout.  I am trying to devise a way to let the API auto renew the token when it is getting close to timeout or already expired.  There are issues with that because the introspection does not always return a correct response.

**Comment by TylerBrinkley** [comment]
I think that burden should be placed on the consumer by implementing some sort of `Timer`.

However, I could see a use for a `Session` created with user credentials to auto retrieve a new token if it has expired after calling the Encompass APIs and then resend the request with the new token.

**Comment by TylerBrinkley** [comment]
I've updated the API proposal to include support for auto retrieval of a new token when making an API call with an expired token. It will then resend the request with the new token.

If you approve of these changes, I can submit a pull request.

**Comment by hfcjweinstock** [comment]
how about a branch that we can work out the details on?

**Comment by TylerBrinkley** [comment]
Sounds good to me.

**Comment by TylerBrinkley** [comment]
Just submitted #13 to implement these changes.

**Comment by TylerBrinkley** [comment]
These changes have been merged.
