### ISSUE TITLE
when setting a value to nullthere is no way to clear isDirty to remove serialization.

### ISSUE THREAD

**Issue by hfcjweinstock** [EncompassRest/EncompassRest#111]
if you take an existing loan and want to clear the GUID, there is no way to remove the isDirty flag from the EncompassID .  this causes  a rest exception.

**Comment by TylerBrinkley** [comment]
I just tried the following and the unit test passed.

```c#
[TestMethod]
public void Loan_Empty_Serialization()
{
    var loan = new Loan();
    Assert.AreEqual("{}", loan.ToJson());
    loan.EncompassId = Guid.NewGuid().ToString();
    Assert.AreEqual($@"{{""encompassId"":""{loan.EncompassId}""}}", loan.ToJson());
    loan.EncompassId = null;
    Assert.AreEqual("{}", loan.ToJson());
}
```

**Comment by TylerBrinkley** [comment]
It won't serialize the id if it's set to `null`.

**Comment by hfcjweinstock** [comment]
might be an old version issue.

**Comment by TylerBrinkley** [comment]
I'm really not sure if changing a `Loan` object's identity is a good idea. For one, the object is cleaned after making an API call so the existing properties wouldn't be serialized if you were going to use that `Loan` object to create a new `Loan` and also the `LoanApis` would still be tied to the old `Loan.EncompassId` value.

**Comment by hfcjweinstock** [comment]
agree, i think we need to make a "Deep Copy" function?

**Comment by hfcjweinstock** [comment]
although, create re initializes everything doesnt it?

**Comment by TylerBrinkley** [comment]
It would but the existing properties wouldn't get serialized in the Create request.

**Comment by hfcjweinstock** [comment]
so we do need an intelligent "create new from"

**Comment by TylerBrinkley** [comment]
I think we could create a "Deep Copy" method on `Loan` that would essentially just use the public serialization method and deserialize it right back to a `Loan` object though I don't like the idea of potentially including PII. Personally I think if you to create loans with some certain values, then you should use the data templates, or else initialize the Loan in a separate method so it can be reused.

**Comment by hfcjweinstock** [comment]
having the PII is not an issue, you already have it.

**Comment by TylerBrinkley** [comment]
But then it would copy over to the new `Loan`

**Comment by hfcjweinstock** [comment]
yup

**Comment by TylerBrinkley** [comment]
Maybe we could just add a warning in the xml documentation that it will copy over all values within the loan, including PII.

**Comment by hfcjweinstock** [comment]
we can.  although it is implied as the entire thing is copied.

**Comment by TylerBrinkley** [comment]
Just so I can get a handle of this, what is the particular use case for this?

**Comment by hfcjweinstock** [comment]
better loan duplication through technology.  or test case loan creation.  or migrating a loan from prod to dev.

**Comment by TylerBrinkley** [comment]
Alright, I suppose that's reasonable.

**Comment by hfcjweinstock** [comment]
looks like the public deserializer has an issue.  cant convert null to decimal.

**Comment by TylerBrinkley** [comment]
do you have a stack trace?

**Comment by hfcjweinstock** [comment]
no, but in the public serialize test it is using  custom serializer to handle null

**Comment by TylerBrinkley** [comment]
Sorry, I don't understand what your issue is.

**Comment by hfcjweinstock** [comment]
worry about it after new year.

**Comment by TylerBrinkley** [comment]
I looked at the stack trace on Slack and it appears there's a serialization/deserialization issue with the NA type.
