### ISSUE TITLE
Create a "CreateFrom" for Extensible objects?

### ISSUE THREAD

**Issue by hfcjweinstock** [EncompassRest/EncompassRest#112]
create a "CreateFrom" for extensible objects that creates a copy of the object but sets all properties that are not default value to isDirty=true.

**Comment by TylerBrinkley** [comment]
Where would this method reside? Would it be an instance method on `ExtensibleObject` like `Clone`?

**Comment by TylerBrinkley** [comment]
How about this?

## Proposed API
```diff
 namespace EncompassRest {
-     public abstract class ExtensibleObject : IDirty, IIdentifiable {
+     public abstract class ExtensibleObject : IDirty, IIdentifiable, ICloneable {
     }
+    public static class Extensions {
+        public static T Clone<T>(this T value) where T : ExtensibleObject;
+    }
 }
```

**Comment by hfcjweinstock** [comment]
ok, but all objects with values would have to be dirty.

**Comment by TylerBrinkley** [comment]
Yes, essentially the `Clone` extension method would call the `ICloneable.Clone` explicit interface implementation which would use the public serialization and deserialization to create a cloned object which by default would make those values dirty.
