### ISSUE TITLE
Duplicate Attribute Error

### ISSUE THREAD

**Issue by amadard** [EncompassRest/EncompassRest#113]
I am running into an error when creating a loan from a new EncompassRest.Loans.Loan object that I am setting up by defining the properties.  The client.Loans.CreateLoanAsync(loan, options) keeps throwing an error:

CreateLoanAsync
{"summary":"Bad Request","details":"Duplicate attribute.","errorCode":"EBS-912"}

I serialized the object into JSON, and removed all NULL properties, and I am able to create the loan using both PostMan and the client.Loans.CreateLoanRawAsync.

**Comment by amadard** [comment]
It's connected to using the Options and including the LoanTemplate.  When I remove that, the error goes away.

Checking with Ellie Mae again with these details.

**Comment by amadard** [comment]
Ellie Mae identified that my URL was incorrect.

The CreateLoanOptions is creating an incorrect QueryString.  It creates:
"loanTemplate=xxx&loanFolder=xxx"

As seen here in LoanOptions class.
            if (!string.IsNullOrEmpty(LoanTemplate))
            {
                queryParameters.Add("loanTemplate", LoanTemplate);
            }

it should be "path=xxx&loanFolder=xxx"

Another issue is that I was passing in the SDK path: "Public:\Companywide\Con 30 Year Fixed", and the Query doesn't allow the : to be included.  I can fix myself, but you may want to clean the LoanTemplate parameter to remove the colon.

**Comment by hfcjweinstock** [comment]
you should have Ellie mae clean up thier try it samples.  all of them mirror what we have now.  I will begin to work on a fix for this

**Comment by amadard** [comment]
I just checked, it looks right on the Developer Portal:

![image](https://user-images.githubusercontent.com/24736715/34395364-71573e4c-eb14-11e7-9b43-82978522c0db.png)

**Comment by TylerBrinkley** [comment]
I created an issue in the Ellie Mae forums [here](https://forum.elliemae.com/index.php?/topic/6457-create-from-loan-template-documentation-issue/).

**Comment by TylerBrinkley** [comment]
The documentation has been updated so that it uses the query parameter "loanTemplate" now. This is no longer an issue.
