### ISSUE TITLE
Add "clean" json Serialization to Objects

### ISSUE THREAD

**Issue by amadard** [EncompassRest/EncompassRest#114]
I can do this myself, but it would be useful if the ToString() method was overridden for the objects to return a clean JSON string that doesn't have all of the null properties.

Example is below that I used to serialize a loan to post in PostMan, without needing to remove the null properties myself.

string json = JsonConvert.SerializeObject(loan, Formatting.None, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore });

**Comment by TylerBrinkley** [comment]
That seems reasonable but the question is should the Formatting be None or Indented. I would think indented.

**Comment by hfcjweinstock** [comment]
the question is of intent of use.  i think formatting None because it is more often going to be consumed by a computer, not read by a human.  if it is read by a human they likely have a tool to format json.

**Comment by TylerBrinkley** [comment]
How about this where default indention is `false`?

## Proposed API
 namespace EncompassRest {
     public class ExtensibleObject {
+        public override string ToString();
+        public string ToString(bool indent);
     }
 }

**Comment by hfcjweinstock** [comment]
ok

**Comment by amadard** [comment]
Looks dandy to me.  I was using None, just because I kept throwing it into a tool to view, but having the option to paste directly into NotePad++ would be useful.

As I always tell Ellie Mae, "Give us the options!"
