### ISSUE TITLE
Add option to auto-retry on timeouts

### ISSUE THREAD

**Issue by TylerBrinkley** [EncompassRest/EncompassRest#117]
We should add the option for clients to auto-retry requests on timeouts.

## Proposed API
```diff
 namespace EncompassRest {
     public class EncompassRestClient {
+        public int TimeoutRetryCount { get; set; } // defaults to 0
+        public event EventHandler<TimeoutRetryEventArgs> TimeoutRetry;
     }
+    public sealed class TimeoutRetryEventArgs : EventArgs {
+        public HttpRequestMessage Request { get; }
+        public HttpResponseMessage TimeoutResponse { get; }
+        public int RetryCount { get; }
+    }
 }
```

In the case of a 504 Gateway Timeout status code the client will automatically resend the request up to `TimeoutRetryCount` number of times which defaults to `0`.

**Comment by hfcjweinstock** [comment]
should this be totally silent internally? should there be a notification to the consumer that retry happened?  should there be a way to know : perhaps add the ability to pass a function to the retry so it can be logged if need be?

**Comment by TylerBrinkley** [comment]
We could add a TimeoutRetry event.

**Comment by hfcjweinstock** [comment]
that works

**Comment by TylerBrinkley** [comment]
What info should be provided in the event args?

**Comment by TylerBrinkley** [comment]
See above for the options provided in the event args.

**Comment by hfcjweinstock** [comment]
why is Retry setable in the eventArg?  it should be an indicator if the system will automatically retry (there are more attepmts left).

**Comment by TylerBrinkley** [comment]
The event will only fire just before a retry, meaning there's at least one more attempt left. Setting `Retry` to false will allow users to explicitly stop the retries in special circumstances.

**Comment by hfcjweinstock** [comment]
i dont see how from an event like that.

**Comment by TylerBrinkley** [comment]
pseudo code
```c#
var response = SendRequest(request);
var retryCount = 0;
while (response.StatusCode == 504 && retryCount < TimeoutRetryCount)
{
    ++retryCount;
    var eventArgs = new TimeoutRetryEventArgs(request, response);
    TimeoutRetry?.Invoke(this, eventArgs);
    if (!eventArgs.Retry) {
        break;
    }
    response = SendRequest(request);
}
```

**Comment by hfcjweinstock** [comment]
that is dangerous in an async environment.  heck it is dangerous in a non-async environment.

**Comment by TylerBrinkley** [comment]
How is that dangerous? It's the same as what Ellie Mae does for cancellations of the `Loan.BeforeCommit` event.

**Comment by hfcjweinstock** [comment]
first, Loan.BeforeCommit is a single threaded event. we are in async environment.  second, there are better ways to handle cancelable events. better off using routedEvents.

sample : https://blogs.msdn.microsoft.com/benwilli/2013/08/01/cancellable-awaiting-on-net-events/

**Comment by TylerBrinkley** [comment]
I still don't see how that code is dangerous as the event is synchronous code. What can go wrong here?

**Comment by hfcjweinstock** [comment]
you are waiting on the event for all handlers to handle that event.

**Comment by TylerBrinkley** [comment]
Yeah. Why's that a problem. We could make the Retry settable to only false or instead remove the Retry property and replace it with a CancelRetry method.

**Comment by hfcjweinstock** [comment]
up to you.  the most i would use the event for would be logging.

**Comment by TylerBrinkley** [comment]
Let's leave out the cancellation for now and if we get a specific user case later we'll address it then.
