### ISSUE TITLE
How to set RestClient Timeout property

### ISSUE THREAD

**Issue by amadard** [EncompassRest/EncompassRest#120]
My RestClients keep timing out, and I can't see a way to increase the timeout.  As far as I see, I only get a client once I have called EncompassRestClient.CreateFromUserCredentialsAsync (or the equivalent), at which point the HTTP Client is already started and I can't update the Timeout.

How am I supposed to set the Timeout?

**Comment by TylerBrinkley** [comment]
Did you try setting the `EncompassRestClient.Timeout` property?

**Comment by amadard** [comment]
Yep.  This throws the below error:

System.InvalidOperationException: 'This instance has already started one or more requests. Properties can only be modified before sending the first request.'

				using (var client = await EncompassRestClient.CreateFromUserCredentialsAsync(_ClientID, _ClientSecret, _InstanceID, _UserID, _UserPassword, EncompassRest.Token.TokenExpirationHandling.RetrieveNewToken))
                {
					client.Timeout = new TimeSpan(0, 1, 0);
					
				}

**Comment by TylerBrinkley** [comment]
Thanks, it looks like we need to create a new `HttpClient` when setting that property.

**Comment by amadard** [comment]
Or, allow it to be a parameter we pass in to the constructor.  Whichever is best for you.

It only is an issue when changing these three properties of the HTTPClient, the only one exposed is TimeOut.

BaseAddress
Timeout
MaxResponseContentBufferSize

**Comment by amadard** [comment]
Added a Pull Request to resolve this.  Please let me know if I am not doing it properly, this is my first time using GIT.
