### ISSUE TITLE
IIdentifiable on items without ID

### ISSUE THREAD

**Issue by amadard** [EncompassRest/EncompassRest#121]
I am wondering why some classes implement the IIdentifiable interface, when they do not have an ID property in the raw JSON, and the object is null for the ID property.

For Example, DisclosureForm implements IIdentifiable, and has the ID property, but the raw JSON doesn't include ID, and the ID property is null in the object.

			"forms": [
				{
					"formName": "Acknowledgement of Intent to Proceed",
					"formType": "eDisclosure"
				}
			],

**Comment by TylerBrinkley** [comment]
It's an internal interface that's being used to get and set id properties of objects that support it. It's not visible publically so consumers need not worry about it.

**Comment by amadard** [comment]
The issue I am running into is that the IIdentifiable is used on classes of objects that don't support it in their JSON.

**Comment by TylerBrinkley** [comment]
It's implemented through explicit interface implementation so it has no influence on what's serialized or deserialized.

**Comment by amadard** [comment]
Back to my original question, Why is it implemented on classes that don't have an ID property in their JSON?

It's confusing, it is unnecessary, and it looks like there is a mistake in the EncompassRest when a class implements IIdentifiable, but the property ID is NULL.

**Comment by TylerBrinkley** [comment]
It just makes things easier since the entity types are auto-generated from the schema. It's an internal interface and so is almost entirely invisible to consumers so it's a non-issue.

**Comment by amadard** [comment]
Uggg... The issue is on Ellie Mae's side.  They include ID in the Schema, but not in the actual JSON.

Emailing them to resolve.

**Comment by amadard** [comment]
Thanks for letting us know.

We will take a look at this specific one. I agree that there are certain inconsistencies around “IDs”, (specifically as other attributes may not be mandatory attributes). Our team has been looking at these and similar issues. 

I will let you know when we resolve these.

Thank you,
Sai Muralidharan
