### ISSUE TITLE
Make DirtyList Implement non-generic IList?

### ISSUE THREAD

**Issue by hfcjweinstock** [EncompassRest/EncompassRest#126]
I have a use case where i am trying to work through the loan without needing to know what specific Type i am working with (yes, lots of reflection)  Creating a generic type  IList<>, and casting the object to it is not something i have been able to find a way to do.  if it were an IList, it would be easy to cast to an IList.

**Comment by TylerBrinkley** [comment]
That should be simple enough. Send in a PR.
