### ISSUE TITLE
DirtyList<> IList broke public serialization

### ISSUE THREAD

**Issue by hfcjweinstock** [EncompassRest/EncompassRest#130]
Message: Test method EncompassRest.Tests.LoanTests.Loan_PublicSerialization threw exception: 
System.ArgumentException: The value "{"assetType":"LifeInsurance","borrowerId":"_borrower1","id":"Asset/0","isEmpty":true}" is not of type "EncompassRest.DirtyValue`1[EncompassRest.Loans.Asset]" and cannot be used in this generic collection.
Parameter name: value

**Comment by TylerBrinkley** [comment]
Yep, this is because the inner list is of type `List<DirtyValue<T>>` but you're using it as if it's a `List<T>`.

**Comment by TylerBrinkley** [comment]
Guess, this one wasn't as simple as I thought it would be.

**Comment by hfcjweinstock** [comment]
i have not done enough with custom serializes to fix this.
