### ISSUE TITLE
Correlation ID for successful API calls

### ISSUE THREAD

**Issue by amadard** [EncompassRest/EncompassRest#138]
I see the EncompassRestException has the correlation ID, but is there anywhere to access the correlation ID for a successful API call?

I am working with Bob on slowness in the API, and he is asking for the correlation ID for successful calls.

**Comment by hfcjweinstock** [comment]
I don't think so because there is no API response to attach it to.

**Comment by amadard** [comment]
One idea I had was to have a CorrelationID property associated with the EncompassRestClient, and every call would update that property.

Or, have a ConcurrentBag (threadsafe list), to hold the CorrelationIDs for all calls using that RestClient.

Thoughts?

**Comment by amadard** [comment]
Also, am I correct that all API calls go through this one method?

ApiObject.SendFullUriAsync

**Comment by TylerBrinkley** [comment]
You could sniff the network traffic with Fiddler.

**Comment by amadard** [comment]
There is a response for every HTTPClient call we make.  E.g. Calling GET loan, that returns a HTTPResponseMessage, which includes the headers, with the x-correlation-id header as well.  EncompassRest just doesn't pay attention to that header unless the response is not a success status code, when it then throws the EncompassRestException, (which grabs the header from the HTTPResponseMessage).

Since Bob is asking for me to provide correlation IDs on successful API calls, (GET is a Success Status Code), I am going to make a branch and store the correlation IDs in the EncompassRestClient.  

Just completed the branch, please review my pull request and let me know what you think.

**Comment by TylerBrinkley** [comment]
Did you try using Fiddler to sniff the network traffic for calls to the APIs? That should be enough for debugging purposes. Honestly, I don't think there's any use for this outside of debugging and thus shouldn't be included in the library.

**Comment by amadard** [comment]
Why do you think that something that is used for debugging purposes should not be included in the library?

**Comment by TylerBrinkley** [comment]
Simply because it adds no value to the library when you can sniff the network traffic when debugging. The only thing I'd consider for this is perhaps adding an API response event to the `EncompassRestClient` class which could also be useful for logging.

**Comment by hfcjweinstock** [comment]
ok...devils advocate here.  I can see uses for having access to other headder information from successful calls. consider it part of the RAW packages.  if i do a create cursor raw, how can i determine the total number available without the headder info.

**Comment by amadard** [comment]
Since this is for logging purposes, I agree with the API response event style.  I will look at the other events in the project for guidance.

Closed the pull and deleted the branch.  I will use forks in the future.

**Comment by hfcjweinstock** [comment]
i peeked at the implementation before it was pulled, and i can see 1 major issue with the implementation.  concurrentbag was not initialized with a maximum size.  that would be a major memory leak.

**Comment by amadard** [comment]
Good reason to have it be an event style, so that there isn't any concern of a max bag size.

**Comment by TylerBrinkley** [comment]
@hfcjweinstock Do you think we need to rethink our Raw methods to return more than just the response body?

**Comment by hfcjweinstock** [comment]
@TylerBrinkley possibly something to think about.  even have an overload to all methods that return a combined response&headder for normal objects?  yes i realize the amount of work im talking about.

**Comment by TylerBrinkley** [comment]
If we go that route, I think they should just replace the existing raw methods, not overload them.

**Comment by amadard** [comment]
Another thought is that the raw could return the HTTPResponseMessage, and then there is a helper to get the string content, and the specific headers that we care about from the HTTPResponseMessage?

**Comment by TylerBrinkley** [comment]
That's more what I was thinking but not expose the `HttpResponseMessage` directly as it will be disposed. Just provide the raw string body, the headers, and the response status code.

**Comment by TylerBrinkley** [comment]
After looking at this, for the raw methods I can get them to return an `HttpResponseMessage` directly without it needing to be disposed.

Question I have is do we want to parse the response to a string and include it as a property of a derived response type or do we want the user to explicitly use the `HttpContent.ReadAsStringAsync` method if they want to retrieve the response body as a string.
