### ISSUE TITLE
TLS 1.2

### ISSUE THREAD

**Issue by TylerBrinkley** [EncompassRest/EncompassRest#141]
From an Ellie Mae email:

This notice is for clients who are using Encompass Developer Connect™ APIs (Application Programming Interfaces) and using browsers or applications via TLS 1.0 or 1.1.  

Ellie Mae is continually upgrading systems and applications to adhere to current industry security standards and protocols in order to protect our clients’ data.  As such, we are deprecating support for TLS 1.0 and TLS 1.1 (Transport Layer Security) and replacing those versions with TLS 1.2 which supports stronger, more secure cipher suites. 

Applications that are compiled with Microsoft® .NET 4.5 will need to be enhanced either in code or via Windows registry to support TLS 1.2. Applications that are compiled with .NET 4.6 or later will support TLS 1.2 by default.

Accessing Ellie Mae’s Encompass Developer Connect APIs using browsers or applications via TLS 1.0 or 1.1 will be disabled as of April 7, 2018.  

Please make sure that you enable your applications with the TLS 1.2 protocol prior to April 7th in order to leverage Ellie Mae’s APIs. 

Please [click here](https://support.microsoft.com/en-us/help/3155464/ms16-065-description-of-the-tls-ssl-protocol-information-disclosure-vu) for instructions on how you can upgrade .NET applications with the TLS 1.2 protocol. 
 
Sincerely, 

Ellie Mae

**Comment by TylerBrinkley** [comment]
As a library is this something we can or should handle?

It looks like the most common way to programmatically specify to use TLS 1.2 by default is by setting the `ServicePointManager.SecurityProtocol` static property which is available in .NET Framework 4.5 which is our lowest supported version but it's only available in .NET Standard 2.0+ and we support down to .NET Standard 1.1. It's also static so it's used by the entire application, not just `EncompassRest`.

Another way is by setting the `HttpClientHandler.SslProtocols` property which is available in .NET Framework 4.7.1+ but we support down to .NET Framework 4.5, and it's also available in .NET Standard 1.3+ but again we support down to .NET Standard 1.1.

**Comment by hfcjweinstock** [comment]
i like the handler method because it only requires standard 1.3 not 2.0
requiring 4.7.1+ i feel like is not a big issue.

**Comment by TylerBrinkley** [comment]
Turns out 4.7.1 has the `HttpClientHandler.SslProtocols` property implemented but just throws a `PlatformNotSupportedException`. Apparently this will be corrected in 4.7.2. For now we can add support in a .NET Standard 1.3 build and then when .NET Framework 4.7.2 is released we can add support there with a new build target. In the meantime users should add this code to their applications if they target the .NET Framework.

`ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls12;`

**Comment by TylerBrinkley** [comment]
According to this new [Microsoft article](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls) it's recommended not to hard code a TLS version in apps. That is what we've done here so since it hasn't been released yet I think we should remove the use of `HttpClientHandler.SslProtocols` as .NET Core 1 & 2 supports TLS 1.2 by default and lower the .NET Standard target version back to 1.1 and add a .NET Framework 4.6 target which doesn't set `ServicePointManager.SecurityProtocol`. The .NET Framework 4.5 target would still implicitly set that property for convenience.
