### ISSUE TITLE
Loan.VirtualFields

### ISSUE THREAD

**Issue by dhtorres** [EncompassRest/EncompassRest#142]
Can I ask how you guys are handling or using VirtualFields? Can they be put into a StringDictionaryInstance?

**Comment by hfcjweinstock** [comment]
currently there is not a defined contract for virtual fields coming from Ellie Mae. we have chosen not to implement virtual fields until EM releases the schema for it so we dont have breaking changes later. 

This is also the case with the EliUCDFields.

**Comment by TylerBrinkley** [comment]
You can however use the `ExtensionData` property like so `loan.ExtensionData["VirtualFields"]` to retrieve it currently.

**Comment by dhtorres** [comment]
This makes sense. Thank you both!
