### ISSUE TITLE
UpdateLoanAsync ?

### ISSUE THREAD

**Issue by cvarro** [EncompassRest/EncompassRest#145]
Is there a trick to using the API client to update a loan?  Do I need to explicitly obtain a lock somehow, like via the SDK?

When I attempt to update a loan with a trivial change, like changing the middle name on a borrower, I keep getting the following error back.  (This is directly from the fiddler response coming from the EM end point)

`{"summary":"Bad Request","details":"You cannot save this file because it has already been locked by another user. Any changes made to this loan will be lost.","errorCode":"EBS-912"}`

I get the same behavior if I use EM's Postman samples directly against their endpoints as well, so I feel like I'm missing something really basic - or their stuff is just really broken.

I've also tried updating the same loan, with the same user, via the classic SDK without problem - so I think I can rule out business rules, permissions, or something similar.  

What am I missing?

```
  public static void Main(string[] args)
        {
            Task.Run(async () =>
            {
                using (var client = await EncompassRestClient.CreateFromUserCredentialsAsync(
                    new ClientParameters("***", "***"),
                    "***", "***", "***"))
                {
                    //grab a loan.
                    var loan = await client.Loans.GetLoanAsync("{69190a57-65fc-411e-8ee3-cf005939e209}");

                    //update that loan.
                    loan.Applications[0].Borrower.MiddleName = "Bob";
                    await client.Loans.UpdateLoanAsync(loan);
                }

            }).GetAwaiter().GetResult();
            Console.WriteLine("complete");
            Console.ReadLine();
        }
    }
```

**Comment by dhtorres** [comment]
Yes, anytime you update the loan you will have to lock it first. You should be able to check for resource lock, lock, and unlock through the API. You can access the loan lock calls from the LoanApis.
GetLocksAsync()
UnlockAsync()
LockAsync()

you can read more about LoanLock here: https://docs.developer.elliemae.com/v2.0/reference#loan-lock

**Comment by TylerBrinkley** [comment]
You shouldn't need to lock the loan to update it. It sounds like another user has the loan opened in the smart client which prevents updates while they have the loan opened.

**Comment by cvarro** [comment]
When I switched to using an account that is not a Super Admin, it works fine.  (although not 100% sure why)  I'll chalk this one up to "not a very good error message coming back from Ellie's API"  Thanks for the help!
