### ISSUE TITLE
c# language and .net standard version errors

### ISSUE THREAD

**Issue by santiagoperdomo** [EncompassRest/EncompassRest#147]
After installation, I have several build errors around c# and .net sdk versons. The two most problematic ones are...

1. Feature 'default literal' is not available in C# 7.0. Please use language version 7.1 or greater.
2. The current .NET SDK does not support targeting .NET Standard 2.0.  Either target .NET Standard 1.6 or lower, or use a version of the .NET SDK that supports .NET Standard 2.0.

I've tried updating my c# language to higher than 7.0, and that didn't work. I'm using VS version 15.6.4. Any ideas? 

THANKS!

![apierror](https://user-images.githubusercontent.com/38016526/38212842-3f32ae28-368d-11e8-8282-9949ac1253c6.jpg)
[restApiErrors.xlsx](https://github.com/EncompassRest/EncompassRest/files/1869148/restApiErrors.xlsx)

**Comment by TylerBrinkley** [comment]
For most users you should only need to install the NuGet package. If you need to source import the library you should install the .NET Core cross platform development workload from the visual studio installer.

**Comment by santiagoperdomo** [comment]
I installed the cross platform and .net desktop development and that fixed all my problems. Thank you Tyler!!!

**Comment by TylerBrinkley** [comment]
That's great to hear.
