### ISSUE TITLE
Object Reference Error calling GetLoanAsync()

### ISSUE THREAD

**Issue by dhtorres** [EncompassRest/EncompassRest#150]
Hi guys, 
I'm getting an Object reference error calling GetLoanAsync().
UPDATE: This is only happening on one loan.

{"summary":"Bad Request","details":"Object reference not set to an instance of an object.","errorCode":"EBS-912"}

Any idea what error code EBS-912 is?

**Comment by hfcjweinstock** [comment]
ebs-912 is a generic error. if you can get the correlation id from the headder, open a ticket with ellie mae and forward the ticket id to me. i can pass it up the food chain.  that error should never happen on getloan.

**Comment by TylerBrinkley** [comment]
Yeah, this is an Ellie Mae error so I'm closing this out. Please let us know if you get it resolved.
