### ISSUE TITLE
Upload attachment - Document Conversion

### ISSUE THREAD

**Issue by amadard** [EncompassRest/EncompassRest#155]
I am waiting on a case from Ellie Mae, but with no response yet I am coming to you.

Can I upload an attachment and have document conversion happen via the API?  I have tried to upload with AttachmentType.Image, but it doesn't change anything.

Thanks!

**Comment by hfcjweinstock** [comment]
from my understanding, that is supposed to be coming in the next release at the end of the month.

**Comment by amadard** [comment]
Ok, thanks!

**Comment by shawnfultz** [comment]
Was this released by EM yet?
