### ISSUE TITLE
Update Milestone

### ISSUE THREAD

**Issue by emcginni13** [EncompassRest/EncompassRest#158]
I am trying to update a milestone using this client.  I am having many issues using either method (update milestone and update milestone raw).  I do get errors from the client when trying to make changes when the loan is locked or a date is wrong, but when a request goes through successfully there is no actual change in encompass, its like the changes were lost.  Is this a known issue or one someone can help with?

**Comment by TylerBrinkley** [comment]
What properties are you trying to update specifically?

**Comment by TylerBrinkley** [comment]
From the forums it looks like you were trying to finish a milestone. This feature has been implemented in the source code but has not been released yet.

**Comment by emcginni13** [comment]
Thanks Tyler, I should have looked at your latest commit before posting.  I pulled your code and found that you implemented a query string that was not in the Ellie docs.  I have it working now, thank you very much and keep up the great work with this awesome library!
