### ISSUE TITLE
Pipeline Filter

### ISSUE THREAD

**Issue by tlambert** [EncompassRest/EncompassRest#16]
FilterTerm does not accept "Fields.745" for instance for canonicalName.  I changed to just a get; set; and it pulls as expected now. Per the developer reference, it will accept canonical names or reporting database names.  I added a method in pipeline.cs to pull all the field definitions so I could see all the available fields
        public async Task<string> FieldDefinitions()
        {
            var message = new HttpRequestMessage(HttpMethod.Get, $"{_apiPath}/loanPipeline/fieldDefinitions");

            var response = await Session.RESTClient.SendAsync(message);
            if (response.IsSuccessStatusCode)
            {
                return await response.Content.ReadAsStringAsync();
            }
            else
            {
                throw new RESTException("FieldDefinitions", response);
            }

        }

 I also created enums for matchType, precision, and sortOrder.  

[FilterTerm.txt](https://github.com/hfcjweinstock/EncompassREST/files/1285082/FilterTerm.txt)
[SortOrderItem.txt](https://github.com/hfcjweinstock/EncompassREST/files/1285083/SortOrderItem.txt)

I'm not a contributer to this repo so will let you verify and add as necessary

**Comment by TylerBrinkley** [comment]
There was a major refactoring to the library, please check it out and report if you think it doesn't resolve your request.

**Comment by hfcjweinstock** [comment]
closing for lack up updates
