### ISSUE TITLE
Present Address?

### ISSUE THREAD

**Issue by cbroadster** [EncompassRest/EncompassRest#166]
First off, thanks for making EncompassRest available. It certainly simplifies the whole aspect of using the APIs...and that is an epic understatement. It is quite awesome.

I have been setting up a test application and if the loan exists, pulling data into it.

Using the 1003 page 1 fields, everything is populated except the Present Address fields.

FR0104,FR0106,FR0107,FR0108,FR0112,FR0124 and the respective CoBorrower IDs return 'Nothing' yet are clearly valued in the loan file. These are standard non indexed EM fields.

What's weird is they show on a pipeline view if added to the cursor/query.

**Comment by TylerBrinkley** [comment]
I've narrowed down the issue. Ellie Mae is returning `null` when `Residence.MailingAddressIndicator` has a value of `false`.

**Comment by cbroadster** [comment]
In further testing, the fields won't populate either way. I was getting a false (boolean) on unchecked and true on checked. The mailing address fields are there either way...just no Present Address.
Hope that helps...thanks for looking into it.
