### ISSUE TITLE
Performance - Get Loan

### ISSUE THREAD

**Issue by sgandewar** [EncompassRest/EncompassRest#17]
Hi Team,

Just wondering if you are getting any performance benefits by using API.

For e.g. GetLoan for single session is taking about 8-9 seconds and for 5 concurrent users its taking 12-14 seconds. I am using this code base only. 

Any advice in this regards will be helpful.

**Comment by TylerBrinkley** [comment]
There was a major refactoring to the library. Please check it out now and report back the performance you're getting. Be sure to set your code to compile in release mode for best performance.

**Comment by hfcjweinstock** [comment]
closing for lack of updates
