### ISSUE TITLE
Curly Braces on Loan GUIDs

### ISSUE THREAD

**Issue by eidylon** [EncompassRest/EncompassRest#182]
Don't know whether this is an issue with EncompassRest, or if it is just an issue you are inheriting from the Ellie Mae APIs. Figured I'd post it though, just to put it out there and make people aware of it.

It seems that when you query the libraries for a set of loans 
(ie `encompassRestClient.Pipeline.ViewPipelineAsync(parameters)` )
when you operate on the returned `LoanPipelineData` objects, such as this: 

    return (
        from LoanPipelineData data in pipeline
        select new LoanInfo() { GUID = data.LoanGuid, IsRetry = false, LastModified = DateTime.Parse(data.Fields[lastModField]) }
    ).ToList();

the loan GUID property (`data.LoanGuid` in the above code) is returned without curly braces, for example:  
**e60f2628-dd31-426c-bd15-02976e4d7d70** .

However, if you go back and try to query based on the loan GUID, such as in this code: 

    public static LoanPipelineData GetFieldValues(string loanguid, List<string> fields) {
        loanguid = Enbrace(loanguid);

        Filter where = new StringFieldFilter(CanonicalLoanField.Guid, StringFieldMatchType.Exact, loanguid, true);

        var loans = GetLoans(fields, where, null);
        return (loans.Count > 0) ? loans[0] : null;
    }

it then **expects** the guid specified as part of the filter to have the curly braces on it. If it does not, it will not find the loan. So the above loan GUID, when used in a filter, needs to be specified as  
**{e60f2628-dd31-426c-bd15-02976e4d7d70}** .

**Comment by TylerBrinkley** [comment]
Thanks for posting this and making others aware of the issue. I'm afraid that's just an artifact of how Ellie Mae's APIs work. Perhaps you can request Ellie Mae to treat querying loan guids without curly braces as if they had them.
