### ISSUE TITLE
Exposing the internal HttpClient

### ISSUE THREAD

**Issue by TylerBrinkley** [EncompassRest/EncompassRest#186]
What are your thoughts on exposing the internal `HttpClient` the `EncompassRestClient` object uses?

The benefits are that users who need to make API calls that are not currently supported by `EncompassRest` can simply use the internal one. This will allow the authentication data to automatically flow over and enable support for the retry logic that the client was setup for.

The `EncompassRestClient.HttpClient` property is currently setup with no `BaseAddress` due to eFolder attachments having a different base path. We should keep this the same requiring users to specify the full API path, e.g. `https://api.elliemae.com/encompass/v1/loans/supportedEntities` vs just `encompass/v1/loans/supportedEntities`.

Also, the `EncompassRestClient.HttpClient` property currently gets replaced when it retrieves a new 
API token. This was done so as to prevent any potential threading issues with replacing the Authorization header but after researching some more I believe it should be thread-safe and anyways a new token should only be retrieved at maximum every 15 minutes or so if the token expires.

**Comment by jesse-weinstock** [comment]
I dont see a problem with exposing the client. the consumers of the rest api are not relying on this implementation to protect them from making mistakes.
