### ISSUE TITLE
Pipeline not returning all expected results

### ISSUE THREAD

**Issue by eidylon** [EncompassRest/EncompassRest#189]
We are running into an odd issue. We are querying the pipeline, but not getting back all of the loans we expect to be returned for a certain query. Our query is basically **return all loans last modified since 01/01/1900**, to effectively return all loans. This isn't something we do regularly, just on first run of this program or as needed, to refresh an external data warehouse. Generally we query **modified since the last run time**. 

The client has roughly **245,000** loans in their Encompass instance. And yet... when I used the `Pipeline.ViewPipelineAsync` method without the limit parameter (which it looks like uses `null` as the limit then) it only returned back about **1000** loans every time, give or take a few.  I tried to force the issue by using the overload with the limit parameter, and specifying `int.MaxValue` for the limit (which is roughly 2 billion). With that way, we only get back about **25,000** every time, give or take a few. 

Here is our method that is calling the pipeline: 

    public static List<LoanPipelineData> GetLoans(List<string> fields, Filter wheres, List<FieldSort> sorts) {
        var client = Connect();
        var parameters = new PipelineParameters(
            wheres,
            fields,
            sorts
        );

        if(Program.RunnableSettings.Verbose) {
            Logging.Write("\n" + JsonConvert.SerializeObject(parameters));
        }

        var pipeline = client.Pipeline.ViewPipelineAsync(parameters, int.MaxValue).Result;
        return pipeline;
    }

And here is the parameters object when saved out to JSON:  

    {
        "Filter": {
            "MatchType": 3,
            "Value": "1900-01-01T00:00:00",
            "Precision": 0,
            "CanonicalName": "Loan.LastModified"
        },
        "Fields": [
            "Loan.LastModified"
        ],
        "SortOrder": [
            {
                "CanonicalName": "Loan.LastModified",
                "Order": 0
            }
        ]
    }

**Comment by jesse-weinstock** [comment]
view pipeline has an elliemae max return.  if you need the full list, you need to use the cursor version and loop through until you get all the results.
