### ISSUE TITLE
Do you have a sample for Getting access token in MVC application

### ISSUE THREAD

**Issue by rostami79** [EncompassRest/EncompassRest#203]
using (var httpClient = new HttpClient())
            {
                using (var request = new HttpRequestMessage(new HttpMethod("POST"), "https://api.elliemae.com/oauth2/v1/token"))
                {
                    var base64authorization = Convert.ToBase64String(Encoding.ASCII.GetBytes("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"));
                    request.Headers.TryAddWithoutValidation("Authorization", $"Basic {base64authorization}");

                    var contentList = new List<string>();
                    contentList.Add("grant_type=authorization_code");
                    contentList.Add("redirect_uri=https://localhost:44321/SummitApps/OAuthTester");
                    contentList.Add("code=" + code);
                    request.Content = new StringContent(string.Join("&", contentList), Encoding.UTF8, "application/x-www-form-urlencoded");

                    var response = await httpClient.SendAsync(request);
                }
            }

I tried the following but I am getting 401 unauthorized 

System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;
            using (var httpClient = new HttpClient())
            {
                using (var request = new HttpRequestMessage(new HttpMethod("POST"), "https://api.elliemae.com/oauth2/v1/token"))
                {
                    var base64authorization = Convert.ToBase64String(Encoding.ASCII.GetBytes("XXXXXXX:XXXXXXXXX "));
                    request.Headers.TryAddWithoutValidation("Authorization", $"Basic {base64authorization}");

                    var contentList = new List<string>();
                    contentList.Add("grant_type=authorization_code");
                    contentList.Add("redirect_uri=https://localhost:44321/SummitApps/OAuthTester");
                    contentList.Add("code=" + code);
                    request.Content = new StringContent(string.Join("&", contentList), Encoding.UTF8, "application/x-www-form-urlencoded");

                    var response = await httpClient.SendAsync(request);
                }
            }

**Comment by TylerBrinkley** [comment]
If you're using `EncompassRest` you only need to use the `EncompassRestClient.Create*` methods. Otherwise you can consult this project's source code or else ask Ellie Mae.
