### ISSUE TITLE
Getting a list of all custom fields...

### ISSUE THREAD

**Issue by eidylon** [EncompassRest/EncompassRest#212]
In the old SDK, I believe there was a way to get a listing of all the custom fields defined in the system.
Is there any way to do that in the API/EncompassRest? 

I see there is a "CustomFields" property of the Loan object, but ideally I want to be able to get a list of the field definitions/descriptors for all the custom fields without needing to open a loan first in order to do so.

This looked promising,..
[EncompassRest.Settings.Loan.LoanSettings](https://github.com/EncompassRest/EncompassRest/blob/599fc19851d33a8004f31d512204bcc5a6ce7e45/src/EncompassRest/Settings/Loan/LoanSettings.cs )

But looking through object browser, I don't actually see that namespace (**EncompassRest.Setttings.Loan**) in the library. I'm using the latest version published on NuGet.

**Comment by TylerBrinkley** [comment]
Yes, it's implemented but not released yet. I'd like to get a 0.5 release out soon with many improvements.

**Comment by TylerBrinkley** [comment]
0.5 has been released with support for this.
