### ISSUE TITLE
Getting "Live" field descriptors?

### ISSUE THREAD

**Issue by eidylon** [EncompassRest/EncompassRest#216]
We have an app which pulls data and creates a data warehouse of Encompass data in Sql Server. 

Part of this process is pulling the FieldDescriptors from Encompass and comparing them to the Sql fields, for some set of fields as defined by the client. We want to pull this from the LIVE data, not from the Reporting DB. In our rush to get an API version out, I just pulled what worked, but now I see that the field list I'm pulling is from the RDB, using `LoanPipline.Pipeline.GetCanonicalNamesAsync()` . 

How do I go about getting a list of field descriptors from the LIVE db, not the RDB?
I see `client.Loans.FieldDescriptors`, which seems to have a way of getting sets of fields (standard, virtual, custom) in Object Explorer, but they don't all show up as available in code. 
![image](https://user-images.githubusercontent.com/5951045/45577214-de356f00-b848-11e8-95e5-9eab5bb02ce0.png)

Even if they were and this would work though, the `EncompassRest.Loans.FieldDescriptor` class doesn't have a Size property that I can see, which is critical to our apps functionality, so we can make the matching Sql Server field the proper size to match Encompass.

I am using the 0.5 version of EncompassRest from NuGet.

**Comment by TylerBrinkley** [comment]
The Standard and Virtual Field Descriptors are static properties. We should make Loans.FieldDescriptors enumerable however.

**Comment by TylerBrinkley** [comment]
Note also that the `StandardFields` and `VirtualFields` are statically populated from the library and are not coming directly from Ellie Mae's API's, this is similar to how the SDK works except the SDK libraries must be updated to the latest to run whereas if you use an older version of EncompassRest you may not get all the current fields. The `CustomFields` are however pulled from Ellie Mae's API's with the `RefreshCustomFieldsAsync` method, again similar to the SDK. The `CustomFields` are initially empty if you don't populate them by either directly calling `RefreshCustomFieldsAsync` or specifying to retrieve them upon creating the `EncompassRestClient` object with the `ClientParameters.CustomFieldsCacheInitialization` property. You can share the `CustomFields` cache between client objects through the `ClientParameters.CommonCache` property.
