### ISSUE TITLE
Add 'Conditions' property to LoanDocument

### ISSUE THREAD

**Issue by yornstei** [EncompassRest/EncompassRest#240]
The Get on the documents endpoint returns, as part of the document object , the conditions the doc may be tied to. Though it's not in the LoanDocument Object. 
From my testing its just adding a `private DirtyList<EntityReference> _conditions;` and `public IList<EntityReference> Conditions { get => GetField(ref _conditions); set => SetField(ref _conditions, value); }` to LoanDocument.cs

**Comment by TylerBrinkley** [comment]
Thanks, as a temporary workaround you can use `(JArray)document.ExtensionData["conditions"]".

**Comment by yornstei** [comment]
My pleasure. Cool, i'll check that out.
