### ISSUE TITLE
AnnotationVisibilityType source comments incorrect for public and personal

### ISSUE THREAD

**Issue by pottermm** [EncompassRest/EncompassRest#259]
```
namespace EncompassRest.Loans.Attachments
{
    /// <summary>
    /// AnnotationVisibilityType
    /// </summary>
    public enum AnnotationVisibilityType
    {
        /// <summary>
        /// Public (Default. Viewable by the user who added it.)
        /// </summary>
        Public = 0,
        /// <summary>
        /// Internal (Viewable by any person with Encompass permissions to view annotations.)
        /// </summary>
        Internal = 1,
        /// <summary>
        /// Personal (Viewable by everyone and is sent as part of documents.)
        /// </summary>
        Personal = 2
    }
}
```
Line /// Public (Default. Viewable by the user who added it.) should read
/// Public (Default. Viewable by everyone and is sent as part of documents.) 
Line /// Personal (Viewable by everyone and is sent as part of documents.) should read:
/// Personal (Viewable by the user who added it.)

**Comment by TylerBrinkley** [comment]
Those comments come directly from Developer Connect's website documentation which seems wrong. Feel free to send a PR to correct this. It's really simple in the browser by clicking the edit icon on the file you want to update.

**Comment by pottermm** [comment]
I do not see in developer connect where the edit icon is.

**Comment by TylerBrinkley** [comment]
Sorry, what I meant was that you can update the EncompassRest documentation. Here's the link to the file which you can then click the edit button in the top right corner to update the file and then send a pull request. https://github.com/EncompassRest/EncompassRest/blob/master/src/EncompassRest/Loans/Attachments/AnnotationVisibilityType.cs
