### ISSUE TITLE
Underwriting Conditions Json Parsing error

### ISSUE THREAD

**Issue by aleeVicFin** [EncompassRest/EncompassRest#262]
Lines in question.

LoanApis api = client.Loans.GetLoanApis("");
List<UnderwritingCondition> conds = await api.Conditions.Underwriting.GetConditionsAsync();

Unexpected character encountered while parsing value: {. Path '[0].ownerRole', line 1, position 638.

I checked the raw function and that seems to work.

**Comment by TylerBrinkley** [comment]
This was fixed in #237 but a release hasn't happened since. I'd like to get out a new release soon, perhaps by next week if not sooner.

**Comment by TylerBrinkley** [comment]
v1.0.0 was released today which fixes this issue.
