### ISSUE TITLE
Serializing Objects On .NET Core

### ISSUE THREAD

**Issue by yornstei** [EncompassRest/EncompassRest#268]
While working on upgrading our app to .net core we updated our reference to EncompassRest as well. However, our code was erroring out when trying to serialize some EncompassRest objects. I thought it might have to do with other installed packages so I created a console app (.net core) and added EncompassRest (as well as Newtonsoft.Json) with the following code and it still errored out. 

```C#
using EncompassRest;
using EncompassRest.Loans;
using Newtonsoft.Json;
using System.Threading.Tasks;

namespace TestEnRestOnDotnetCore
{
    class Program
    {
        static async Task Main(string[] args)
        {
            using (EncompassRestClient client = await EncompassRestClient.CreateFromAccessTokenAsync(new ClientParameters(myKey, mySecret), myToken))
            {
                Loan loan = new Loan(client, loanGuid);

                var pairs = await loan.LoanApis.BorrowerPairs.GetBorrowerPairsAsync();

                string sJson = JsonConvert.SerializeObject(pairs);
            }
        }
    }
}
```
Exception: System.MissingMethodException: 'Method not found: 'Newtonsoft.Json.SerializationBinder Newtonsoft.Json.JsonSerializer.get_Binder()'.'

I realized it's the Newtonsoft.Json package that causing the error; any version of Newtonsoft.Json greater than 9.0.1 causes the error. (even though the dependencies for EncompassRest states Newtonsoft.Json (>= 9.0.1))

The same process (creating a console app, adding EncompassRest, adding Newtonsoft.Json with the above code) on .net framework, works fine with any version of Newtonsoft.Json greater than 9.0.1 , only on .net core is this an issue. 

Due to other projects dependencies we need a at least version 10.0.1 of Newtonsoft.Json. 

Any idea why the .net core with higher versions of Newtonsoft.Json would error out when serializing EncompassRest objects or how we could go about this? 

Thanks.

**Comment by yornstei** [comment]
After forking the repo and changing it to a newer version of Newtonsoft.Json, I realized that there's two fields in the JsonSerializer - 'Binder' and 'TypeNameAssemblyFormat' that are obsolete. When I changed them to 'SerializationBinder' and 'TypeNameAssemblyFormatHandling' (code below), built the repo and used the new dll, I didn't have any issue serializing EncompassRest objects. 

```C#
            var publicSerializer = new JsonSerializer
            {
                SerializationBinder = existingSerializer.SerializationBinder,
                //Binder = existingSerializer.Binder,
                CheckAdditionalContent = existingSerializer.CheckAdditionalContent,
                ConstructorHandling = existingSerializer.ConstructorHandling,
                Context = existingSerializer.Context,
                ContractResolver = s_publicContractResolver,
                Culture = existingSerializer.Culture,
                DateFormatHandling = existingSerializer.DateFormatHandling,
                DateFormatString = existingSerializer.DateFormatString,
                DateParseHandling = existingSerializer.DateParseHandling,
                DateTimeZoneHandling = existingSerializer.DateTimeZoneHandling,
                DefaultValueHandling = existingSerializer.DefaultValueHandling,
                EqualityComparer = existingSerializer.EqualityComparer,
                FloatFormatHandling = existingSerializer.FloatFormatHandling,
                FloatParseHandling = existingSerializer.FloatParseHandling,
                Formatting = existingSerializer.Formatting,
                MaxDepth = existingSerializer.MaxDepth,
                MetadataPropertyHandling = existingSerializer.MetadataPropertyHandling,
                MissingMemberHandling = existingSerializer.MissingMemberHandling,
                NullValueHandling = existingSerializer.NullValueHandling,
                ObjectCreationHandling = existingSerializer.ObjectCreationHandling,
                PreserveReferencesHandling = existingSerializer.PreserveReferencesHandling,
                ReferenceLoopHandling = existingSerializer.ReferenceLoopHandling,
                ReferenceResolver = existingSerializer.ReferenceResolver,
                StringEscapeHandling = existingSerializer.StringEscapeHandling,
                TraceWriter = existingSerializer.TraceWriter,
                TypeNameAssemblyFormatHandling = existingSerializer.TypeNameAssemblyFormatHandling,
                //TypeNameAssemblyFormat = existingSerializer.TypeNameAssemblyFormat,
                TypeNameHandling = existingSerializer.TypeNameHandling
            };
```

Obviously this will break EncompassRest if Newtonsoft.Json is less then 10.0.1, so I'm not sure you'd like to upgrade.

**Comment by TylerBrinkley** [comment]
I was able to replicate this with Newtonsoft.Json 11.0.2. I think we should consider upgrading the Json.NET minimum version to 11.0.2 which is the first major version for first class .NET Standard 2.0 support and additionally apply the changes @yornstei suggests. Since we're not following semantic versioning religiously I think it would be fine to update the dependency in a minor version update. What do you think @gashach?
