### ISSUE TITLE
Using Filters with multiple conditions?

### ISSUE THREAD

**Issue by walkeryan** [EncompassRest/EncompassRest#27]
I've looked through the Test cases but I can't find any that have filters with multiple field conditions. I'm still fairly new to REST API's. Is there a way to pass more than one Filter, or create a filter with multiple fields?

Here is my code currently:
var filter = new StringFieldFilter("Loan.CurrentMilestoneName", StringFieldMatchType.Exact, "Started");
var fields = new[] { "Loan.CurrentMilestoneName", "Fields.3142", "Loan.LastModified" };
var cursor = await client.Pipeline.CreateCursorAsync(new PipelineParameters(filter, fields));

Is there a forum we can use to discuss this project, I'd hate to keep posting in Issues for items that could potentially not be issues.
Thanks again.

**Comment by TylerBrinkley** [comment]
Just like with the SDK you can call the `And` and `Or` methods to create a query with multiple filters. These things will be addressed with more documentation in the future but we're just not there yet. Thanks.

If you're on basecamp you can post there or on the encompassdevs slack group. Note: I don't have access to add you to those groups.

**Comment by TylerBrinkley** [comment]
Here's a link on the Ellie Mae forums to help you get joined up on the encompassdevs slack group. http://forum.elliemae.com/index.php?/topic/6099-slack-channel-for-encompass-devs-join-us/
