### ISSUE TITLE
Upload Attachment Not Associating to Document (requiring additional call)

### ISSUE THREAD

**Issue by leerodgers** [EncompassRest/EncompassRest#296]
We are trying to use the code below to upload an attachment to a document.  I believe the ASsignDocument may be an extra call.  The fact that we are setting the Document / Entity Reference seems like it should be attaching it on upload.  See the code sample below.  The last line seems unnecessary but without it, the attachment goes into the unassigned attachment bucket.
 ```
var newAttachment = new LoanAttachment(fileInfo.Name.Replace(fileInfo.Extension, "")
                , fileInfo.Name, AttachmentCreateReason.Upload);
            newAttachment.Document = new EncompassRest.EntityReference(containerId, EncompassRest.EntityType.Document);
            var attachmentID = await apis.Attachments.UploadAttachmentAsync(newAttachment,fileData);
            await apis.Documents.AssignDocumentAttachmentsAsync(containerId, EncompassRest.AssignmentAction.Add,
                new List<EncompassRest.EntityReference>() { new EncompassRest.EntityReference(attachmentID, EncompassRest.EntityType.Attachment) });
            
```

**Comment by TylerBrinkley** [comment]
I suggest you open a case with Ellie Mae to support associating an attachment with a document upon upload. This isn't something we can fix.

**Comment by leerodgers** [comment]
@TylerBrinkley  - I'm going to dig into this a little more.  We were using the Ellie API and were not making the additional attach call. i will provide some example code and also dig into the source here a bit.

**Comment by TylerBrinkley** [comment]
Hmm, so you had it working before with the Ellie Mae .NET Bindings? If so, then it would be helpful to know what we can do in EncompassRest to make it work here as well.

**Comment by leerodgers** [comment]
Exactly, we have a release tomorrow so we might not get to dig into it for a few days. We'll update the issue once we figure it out.

**Comment by leerodgers** [comment]
So it looks like we are just setting the documentId on the media contract.  We get that off of the EfolderDocumentContract.DocumentID. We then set the DocumentRefId on the mediacontract. 

```
            var mediaContract = new EFolderMediaUrlContract();
            mediaContract.DocumentRefId = documentId;
            mediaContract.Title = fileInfo.Name.Replace(fileInfo.Extension,"");
            mediaContract.FileWithExtension = fileInfo.Name;

```
We then call the upload attachments call

`await attachmentsApi.UploadAttachmentAsync(loanGuid,"", mediaContract);`

We upload the bytes. and thats it.  We don't make the associate attahcment call in that case.  But in EncompassRest we have to make that last call.  

EncompassRest nicely merges those 2 create media url and byte array upload into a single API call but we lose that ability to chuck in that documentRefId.

In EntityRest we are setting the .Document object as an EntityReference but it looks like thats not making it into that DocumentRefId spot.

**Comment by TylerBrinkley** [comment]
Could you try adding the following code before making your request?

```c#
attachment.ExtensionData["documentRefId"] = documentId;
```

If that works for you then we can add a strongly-typed `DocumentRefId` property to `LoanAttachment`.

**Comment by leerodgers** [comment]
That worked!

**Comment by leerodgers** [comment]
@TylerBrinkley  - FYI - We are encountering issues with DocumentRefId and loan locking.  Uploading an attachment with this value set is causing a loan lock conflict when making a separate call after it does not.  We are not going to use this yet, and open a ticket will Ellie about the issue. We need to keep the loan locked.

**Comment by TylerBrinkley** [comment]
@leerodgers Thanks for the heads up. Keep us posted.
