### ISSUE TITLE
TypeInitializationError creating EncompassRestClient

### ISSUE THREAD

**Issue by chris-thompson-go** [EncompassRest/EncompassRest#300]
I upgraded Enums.Net with the NuGet Package Manager and now I am getting a TypeInitializationError when I invoke EncompassRestClient.CreateAsync.  I am not getting it everywhere in every solution.  I removed EncompassRest, Enums, and Newtonsoft and then reinstalled EncompassRest and then pressed the Upgrade button on Enums.Net and getting the error again.  Has anybody seen this?

**METHOD CALL**
        EncompassRestClient apiClient = EncompassRestClient.CreateAsync(cp,
                t => t.FromUserCredentialsAsync(sessionInfo.ServerId, sessionInfo.UserId, sessionInfo.Password.ToUnsecureString())).Result;

**STACKTRACE**
System.AggregateException: One or more errors occurred. ---> System.TypeInitializationException: The type initializer for 'CustomContractResolver' threw an exception. ---> System.MissingMethodException: Method not found: '!!0 EnumsNET.Enums.Validate(!!0, System.String)'.
  Stack Trace: 
    EnumJsonConverter.ctor(EnumFormat enumFormat)
    CustomContractResolver.cctor() line 352
    --- End of inner exception stack trace ---
    CustomContractResolver.GetBackingFieldInfo(Type type, String propertyName) line 432
    PrivateContractResolver.PopulateShouldSerializeMethod(JsonProperty property, PropertyInfo propertyInfo) line 548
    CustomContractResolver.CreateProperty(MemberInfo member, MemberSerialization memberSerialization) line 373
    DefaultContractResolver.CreateProperties(Type type, MemberSerialization memberSerialization)
    DefaultContractResolver.CreateObjectContract(Type objectType)
    PrivateContractResolver.CreateObjectContract(Type objectType) line 503
    ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
    DefaultContractResolver.ResolveContract(Type type)
    JsonSerializerInternalReader.GetContractSafe(Type type)
    JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
    JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
    JsonHelper.FromJson[T](TextReader reader) line 80
    <ReadAsAsync>d__27`1.MoveNext() line 334
    --- End of stack trace from previous location where exception was thrown ---
    ExceptionDispatchInfo.Throw()
    TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    <SendFullUriAsync>d__41`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    ExceptionDispatchInfo.Throw()
    TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    <GetTokenAsync>d__20.MoveNext() line 146
    --- End of stack trace from previous location where exception was thrown ---
    ExceptionDispatchInfo.Throw()
    TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    <CreateAsync>d__0.MoveNext() line 133
    --- End of inner exception stack trace ---
    Task`1.GetResultCore(Boolean waitCompletionNotification)
    ApiClientProvider.GetClient(SessionInfo sessionInfo, Nullable`1 timeoutSecs) line 23

**Comment by TylerBrinkley** [comment]
This is due to breaking changes in `Enums.NET` v3. You will need to keep referencing `Enums.NET` v2.3.2 with Encompass until the next release which will reference `Enums.NET` v3.

**Comment by chris-thompson-go** [comment]
Thanks
