### ISSUE TITLE
Token Sharing / Recycling in Azure Functions

### ISSUE THREAD

**Issue by mgerety** [EncompassRest/EncompassRest#302]
More of a question than an issue:

We're setting up a queue triggered azure function to synchronize some data from encompass.  Depending on traffic, azure could spawn any number of parallel instances, and i'm not able to find a reliable way to create a singleton instance of the encompassRest client that could be used across Azure Functions instances.

Ideally, we'd like to re-use tokens so we're not exhausting token requests.  Is there any way to:

We'd ideally want our flow to look something like this:
- Check if token is in cache
- If so, check if token is expired
- If not, create client using token
- If no token or expired, get a new token, cache the new token
- Inject that token into client somehow
--------
Any guidance on that?

**Comment by TylerBrinkley** [comment]
I'm assuming there's a place you can store a token in Azure, correct?

Assuming that you could do something like this.

```c#
var initializing = true;
using (var client = await EncompassRestClient.CreateAsync(
    new ClientParameters("apiClientId", "apiClientSecret"),
    async tokenCreator =>
    {
        if (initializing)
        {
            initializing = false;
            return GetStoredToken(); // However that's achieved in Azure
        }
        var newToken = await tokenCreator.FromUserCredentialsAsync("encompassInstanceId", "encompassUserId", "encompassPassword");
        StoreToken(newToken); // However that's achieved in Azure
        return newToken;
    }))
{
    // Use client, if token is expired it will automatically retrieve a new token using
    // the delegate provided above and then resend the original resend request
}
```

**Comment by mgerety** [comment]
Tyler,

This is perfect -- Thanks, I'll give it a shot.
