### ISSUE TITLE
Thread Safety

### ISSUE THREAD

**Issue by TylerBrinkley** [EncompassRest/EncompassRest#31]
When I originally started working on this project I tried to make everything thread-safe but now I believe that's a bit overkill and not actually attainable, especially with dirty-checking and populating values from json.

I'm thinking the only things that need to be thread-safe are the `EncompassRestClient` as well as its properties and sub-properties.

I don't think objects like `Loan`, `LoanAttachment`, or `LoanDocument` need to be thread-safe.

Any thoughts?

**Comment by hfcjweinstock** [comment]
perhaps the collections should be thread safe?

**Comment by TylerBrinkley** [comment]
Essentially when I'm mentioning thread-safety is that the objects can be shared and used safely across multiple threads without any stepping on toes. That's why I've used the `Interlocked.CompareExchange` methods throughout.

I don't think `Loan`s should be shared across multiple threads due to potential issues with dirty-checking and populating loans with returned json results.

**Comment by hfcjweinstock** [comment]
the reason i suggested collections being thread safe, is because i can come up with scenarios where working on the same loan but multiple parts of a collection would happen.  I think i agree that the object dont need to be thread safe.  i cannot convince myself of a good use of threaded changes to a single loan.

**Comment by TylerBrinkley** [comment]
So when you say collection, do you mean a collection property of a loan or a collection of loans?

**Comment by hfcjweinstock** [comment]
a collection property : custom fields, log, etc.

**Comment by TylerBrinkley** [comment]
Could you please explain to me a scenario where multi-threading would be useful for those? Thanks.

**Comment by hfcjweinstock** [comment]
possibly bulk updating multiple borrower pairs.  the more i think about it, the less situations i find for an individual "Loan"

**Comment by TylerBrinkley** [comment]
I'd like to submit a PR that removes the existing thread-safety code for `Loan` and its properties. Does that sound good?

**Comment by hfcjweinstock** [comment]
yeah.
