### ISSUE TITLE
ELM-4001 error on GetMilestonesAsync()

### ISSUE THREAD

**Issue by ChuckFleming** [EncompassRest/EncompassRest#313]
Good Afternoon!

Before getting into my issue, just wanted to say thank you for all the work on EncompassRest. This has greatly simplified the process of integrating my companies software with Encompass. 

I'm attempting to grab Milestone Data from a loan using GetMilestonesAsync in the LoanApis, but I'm getting the error below. I also tried GetMilestonesAsyncRaw with the same error occurring. I'm able to set fields, get fields, get document information, get associates, borrower information; essentially everything else works that I've tried except for this. 

I was wondering if anyone else has experienced a similar error, or if I'm just doing something incorrect on my end? I looked up the "ELM-4001" error but it appears to be generic. However, I noticed a line in the error with "Mapping types" and wasn't sure if this could be due to a mismatch in the value being sent, and what the API is expecting?

Exception encountered: 'System.AggregateException: One or more errors occurred.
---> EncompassRest.EncompassRestException: GetMilestonesAsync: 7e8e384d-cbd2-4d4
3-8d7a-a68291f8a255
{"summary":"Internal Server Error","details":"\u000d\u000a\u000d\u000aMapping ty
pes:\u000d\u000aMilestoneLog -> String\u000d\u000aElli.Domain.Mortgage.Milestone
Log -> System.String\u000d\u000a\u000d\u000aDestination path:\u000d\u000aList`1[
1].startDate1[1]\u000d\u000a\u000d\u000aSource value:\u000d\u000aElli.Domain.Mor
tgage.MilestoneLog","errorCode":"ELM-4001"}
   at EncompassRest.ApiObject.<SendFullUriAsync>d__41`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotifica
tion)
   at System.Threading.Tasks.Task`1.get_Result()
   at EncompassTesting.Program.PerformEncompassTasks(String apiClientId, String
secretKey, String lenderAPIClientID, String loanId) in C:\Source\EncompassTestin
g\EncompassTesting\Program.cs:line 309
---> (Inner Exception #0) EncompassRest.EncompassRestException: GetMilestonesAsy
nc: 7e8e384d-cbd2-4d43-8d7a-a68291f8a255
{"summary":"Internal Server Error","details":"\u000d\u000a\u000d\u000aMapping ty
pes:\u000d\u000aMilestoneLog -> String\u000d\u000aElli.Domain.Mortgage.Milestone
Log -> System.String\u000d\u000a\u000d\u000aDestination path:\u000d\u000aList`1[
1].startDate1[1]\u000d\u000a\u000d\u000aSource value:\u000d\u000aElli.Domain.Mor
tgage.MilestoneLog","errorCode":"ELM-4001"}
   at EncompassRest.ApiObject.<SendFullUriAsync>d__41`1.MoveNext()<---

It's also probably worth mentioning that I'm connecting to an EllieMae provided test instance that they administrate, Encompass v19.4.0.5. 

Any help or ideas would be greatly appreciated. 

Thanks!
Chuck

**Comment by gashach** [comment]
This looks like an elliemae server issue. have you opened a ticket?

**Comment by ChuckFleming** [comment]
Thank you for the advice gashach! I reached out to my EM Rep and he confirmed that the Milestone dates were corrupted. Once these dates were fixed, everything worked as expected. 

Thank you again for the help!
