### ISSUE TITLE
Allow writing to read-only field locally through use of a flag

### ISSUE THREAD

**Issue by TylerBrinkley** [EncompassRest/EncompassRest#315]
Currently, if you try to set the value of a read-only field with the `Loan.Fields` property an `InvalidOperationException` occurs indicating the field is read-only. This is to allow users to get a good error message on the client side prior to trying to send the update to the API.

For generational purposes, instead of updates, such as with unit testing it would be useful to be able to set the value of read-only fields of a local `Loan` object. I propose adding a flag as such to allow writes to read-only fields locally.

```diff
 namespace EncompassRest.Loans {
     public sealed class LoanFields {
+        public bool AllowWritesToReadOnlyFieldsLocally { get; set; }
     }
 }
```

**Comment by gashach** [comment]
how would this be implemented?
and why do we want to manage this?
and what about cases where a user may not be able to write but the field is writable

**Comment by TylerBrinkley** [comment]
Current behavior is to throw that exception when trying to set a read-only field. The indication of whether a field was read-only or not was already being stored in the library so it was done like that to provide users a good error message prior to sending their loan update.

What I'm proposing is that this new property will allow us to essentially disable that protection if they don't want it, such as when generating sample `Loan` objects for unit testing.

Here's the relevant code. https://github.com/EncompassRest/EncompassRest/blob/master/src/EncompassRest/Loans/LoanField.cs#L149

**Comment by gashach** [comment]
ok
