### ISSUE TITLE
Updating with BorPair specific FieldIds

### ISSUE THREAD

**Issue by chris-thompson-go** [EncompassRest/EncompassRest#320]
Is there a way to update BorPair specific fields using a FieldId?

**Comment by yornstei** [comment]
Yes. loan.Fields["4000#2"].Value = "Joe"; 
Check out this unit test [https://github.com/EncompassRest/EncompassRest/blob/21d4536f195a321cd1788a95d36ca66dee3db263/src/EncompassRest.Tests/LoanTests.cs#L913] showing this functionality. 
In general, if you don't see something in the wiki, check out the tests; there's a lot of information on using this library there.

**Comment by TylerBrinkley** [comment]
Thanks for opening the issue. I've added a small section on the [wiki](https://github.com/EncompassRest/EncompassRest/wiki/Field-ID-Support#borrower-pair-field-support) to explain this.
