### ISSUE TITLE
SDK Required

### ISSUE THREAD

**Issue by mblandgithub** [EncompassRest/EncompassRest#327]
Does this api support really old versions of encompass (15.2.0.9 sp 3)?

Does this require the Encompass SDK to be installed?  Not sure if we have that nor do I think they would sell it to us since we are on an old system and out of support.

**Comment by TylerBrinkley** [comment]
No, the API's are not supported on older versions of encompass.

The SDK is not required with this package. The SDK is only used by us for creating the package when re-generating the entities for when updates are made to the API's to populate missing field descriptions and virtual field information.

**Comment by mblandgithub** [comment]
Is there a way to get a version that works with this older version of encompass?  We need to export some load data to a fannie 3.2 format and need access to the data.

**Comment by TylerBrinkley** [comment]
The Encompass API's do not currently support exporting files to Fannie Mae 3.2 format. The SDK can do that though.

**Comment by mblandgithub** [comment]
But I can use the api to pull the data needed to build the 3.2 file with custom code.  Since I do not have access to the sdk that is my only option.

**Comment by TylerBrinkley** [comment]
The API is not supported for such an old version of Encompass. For one I believe you need to be using a hosted version of Encompass which mandates you're on a recent version.
