### ISSUE TITLE
API's Collection Return Type

### ISSUE THREAD

**Issue by TylerBrinkley** [EncompassRest/EncompassRest#33]
Currently the .NET API returns a `List<T>` for API calls that return a collection such as the `Pipeline.ViewPipelineAsync` method. Do you think this should be changed to something like `IList<T>` instead to mirror what was done for collections inside of the objects that are returned like `Loan.CustomFields`?

I suppose semantically it doesn't matter as we're unlikely to need to change the return type but the cohesiveness with the object's collections seems beneficial. Thoughts?

**Comment by TylerBrinkley** [comment]
@hfcjweinstock do you have any thoughts on this?

**Comment by hfcjweinstock** [comment]
I think the IList is the way to go. It gives one more layer of standardisation.

**Comment by TylerBrinkley** [comment]
Sounds good to me. I'll submit the PR.

**Comment by TylerBrinkley** [comment]
Ugh, after looking at some other libraries I'm kind of torn on this. Some other collection returning libraries return a `List<T>` whereas some return an `IEnumerable<T>`. I beginning to think we should just leave it.

**Comment by nturpchinoff** [comment]
Here's what I found on this:

> "IEnumerable describes behavior, while List is an implementation of that behavior. When you use IEnumerable, you give the compiler a chance to defer work until later, possibly optimizing along the way. If you use ToList() you force the compiler to reify the results right away."

My vote would probably be to use IEnumerable.

**Source**: https://stackoverflow.com/questions/3628425/ienumerable-vs-list-what-to-use-how-do-they-work?answertab=votes#tab-top

**Comment by hfcjweinstock** [comment]
I dont always ToList, i have use cases that dont use it for deferred processing.  I agree in IEnumerable.

**Comment by TylerBrinkley** [comment]
The thing is the deserializer `Json.NET` is already creating a `List<T>` so why not just expose it as such. Then we'll have a `Count` property and users will know they're able to modify the collection as it's created just for their call.

**Comment by hfcjweinstock** [comment]
changing my vote to List<>
