### ISSUE TITLE
Which API can return the Mismo 2.3 or 3.2 or 3.4 Files

### ISSUE THREAD

**Issue by zaher-elrody** [EncompassRest/EncompassRest#332]
I am working with EncompassRest nuget package and i was able to setup the code as you mentioned it in the "Getting started" section (with right credentials provided) and was able to get a Loan Guid Id (by Pipeline.ViewPipelineAsync), and using this loan guid id i got the loan data by Loans.GetLoanAsync.
Now from this loan or its id is there an API that returns the MISMO format of IT (version 2.3 or 3.2 or 3.4) ?

**Comment by TylerBrinkley** [comment]
This API is not documented but it appears from this post in the forums that it is supported. https://forum.elliemae.com/index.php?/topic/8672-how-can-we-export-fnm-32/&tab=comments#comment-31590

**Comment by gashach** [comment]
this is cool. caviat: TEST. verify. undocumented endpoints have not guarantee of working or not changing.

**Comment by zaher-elrody** [comment]
@TylerBrinkley as i am outside of the US i don't have direct access to the above block. But anyway I managed to see the content of it and what it says that I should call the API:
 {{API_SERVER}}/encompass/v1/loans/{{LoanGuid}}?format=EXPORT.FANNIE32
My question is what is the {{API_SERVER}} i should call?
Is there another way to get this MISMO format from the Loan itself by calling GetLoan(LoanGuidId)?

**Comment by TylerBrinkley** [comment]
{{API_SERVER}} in this case would be `https://api.elliemae.com`. I'd imagine it'd be possible to manually create the MISMO file from the contents of the `GetLoan` call but you'd have to figure out the mapping.

**Comment by zaher-elrody** [comment]
Ok I was able to get the MISMO format using the following API:
`using (var client = await EncompassRestClient.CreateAsync(
	new ClientParameters(_clientConfig.ClientId, _clientConfig.ClientSecret),
	tokenCreator => tokenCreator.FromUserCredentialsAsync(_clientConfig.InstanceId, _clientConfig.Username, _clientConfig.Password)))
{
	var request = new RestRequest($"/encompass/v1/loans/{loanId}?format=EXPORT.AUS24");                	

	var restClient = new RestClient(new Uri("https://api.elliemae.com"));
	restClient.AddDefaultHeader("Accept", "application/json");
	restClient.AddDefaultHeader("Authorization", $"Bearer {client.AccessToken.Token}");

	var response = await restClient.ExecuteGetTaskAsync(request);	
}`

As you notice first thing we need is to pass the Access Token to the Authorization header, 
And for the query string param "format" I chose EXPORT.AUS24 as it returns MISMO2.4.
Below are the Supported formats: 
EXPORT.FANNIE32, EXPORT.FREDDIE42, EXPORT.AUS24, EXPORT.CLOSING231.LOCKFORM, EXPORT.UCD, EXPORT.LOANDELIVERY.FREDDIE, EXPORT.LOANDELIVERY.FANNIE, EXPORT.CLOSING26.EXTENDED, EXPORT.CD33, EXPORT.LE33, EXPORT.UCD.FINAL

**Comment by TylerBrinkley** [comment]
you could also use `var response = await client.Loans.GetLoanRawAsync(loanId, "format=EXPORT.AUS24")`.

**Comment by zaher-elrody** [comment]
Ok thanks for the tip.
