### ISSUE TITLE
Edit Users & Personas

### ISSUE THREAD

**Issue by jamespfinn** [EncompassRest/EncompassRest#333]
Does EncompassRest and the Ellie Mae REST API allow the creation/update/deletion of users and personas via REST methods or are you forced to used the SDK?

**Comment by TylerBrinkley** [comment]
There may be some API's out there that allow modifying users or personas, such as a POST, PATCH, or DELETE request to the equivalent GET API's, but they are undocumented so use at your own risk as they may not work in the future and good luck getting Ellie Mae to support them.
