### ISSUE TITLE
Marking an attachment Inactive?

### ISSUE THREAD

**Issue by eidylon** [EncompassRest/EncompassRest#336]
We have some apps that upload attachments to named documents. I think I've got all SDK code switched over to using EncompassRest, but there's one piece I don't see. 

Before we upload a new file to the Document, we mark all the previous files inactive. (Active = False). 
Is there a way to do this right now in EncompassRest? I see the Active property in the src, but don't see anyway that I can find to set an Attachment's Active property = False and commit it back.

**Comment by TylerBrinkley** [comment]
Does setting the `LoanAttachment.IsActive` property to `false` and sending the attachment in an `UpdateAttachmentAsync` call not work?

**Comment by eidylon** [comment]
I'll check that out, thanks! I've been figuring out most of what I've needed just by studying the source/tests, but couldn't figure that one out. I'll give it a shot and see what happens. Thank you. 👍🏼👍🏼

**Comment by eidylon** [comment]
Seems to have worked, yup. Thanks.
