### ISSUE TITLE
Concurrency limit exception - GetLoanAsync

### ISSUE THREAD

**Issue by Praveengora** [EncompassRest/EncompassRest#338]
Hello,

While using GetLoanAsync, this exception occurs sporadically for some of the loans and none of these loans are saved or synced at the same time by users. The same exception occurs while updating the loans: UpdateLoanAsync. Have used 10 loans for this test. Can you please advise on this.

`EncompassRest.EncompassRestException: GetLoanAsync: c927cfb6-8075-4c5a-bcf7-f5497b48465e - 429: 429 - CorrelationId: 838fb389-99a6-446b-9b07-6973c80a607c
{"code":"100002","message":"Client has exceeded the concurrency limit or daily quota. Please contact your account manager."}
   at EncompassRest.ApiObject.<SendFullUriAsync>d__42.1. MoveNext() in C:\Users\tbrinkley\source\repos\EncompassRest\EncompassRest\src\EncompassRest\ApiObject.cs:line 146
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EncompassRest.Loans.Loans.<GetLoanAsync>d__11.MoveNext() in C:\Users\tbrinkley\source\repos\EncompassRest\EncompassRest\src\EncompassRest\Loans\Loans.cs:line 335
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()`

Code snippet:

public void Main()
{
    Task.Run(async () => {
        // async code 
   }).GetAwaiter().GetResult();
}

using (var client = await EncompassRestClient.CreateAsync(new ClientParameters(_apiClientId, _apiClientSecret), tokenCreator => tokenCreator.FromUserCredentialsAsync(_instanceId, _userId, _userPassword)))
{
   var loanData = await client.Loans.GetLoanAsync(loanId));
   ...
}

I’m using the version 1.2.1 in console app.

**Comment by gashach** [comment]
EllieMae has concurrent API call limits. you are reaching them. you need to have safeguards and retries in your code to handle these. or contact elliemae to have the concurrency limits adjusted.

**Comment by zackimball** [comment]
If I remember correctly, and it's been a hot minute since I've used the Ellie Mae API, the concurrency limit is something like 30 concurrent requests. In the past, I've used Polly to help deal with this as a resiliency issue. Hope this helps!

**Comment by Praveengora** [comment]
> EllieMae has concurrent API call limits. you are reaching them. you need to have safeguards and retries in your code to handle these. or contact elliemae to have the concurrency limits adjusted.

@gashach Thank you for the suggestion, will give it a try. If a same token is used for the api calls GetLoan, UpdateLoan, UpdateEFolder etc, there might be a possibility of concurrency issue due to EMs concurrency limit. But in this case, a new token is created for each api call and there is no issue with client dispose as well, not sure about the root cause yet.

**Comment by Praveengora** [comment]
> If I remember correctly, and it's been a hot minute since I've used the Ellie Mae API, the concurrency limit is something like 30 concurrent requests. In the past, I've used Polly to help deal with this as a resiliency issue. Hope this helps!

@zackimball Thank you for the info, will get in touch with EM.

**Comment by Praveengora** [comment]
Just an update: There is no concurrency issue in Production environment. It seems the issue was on the concurrency limit set on the test environment that was causing the exception.
