### ISSUE TITLE
trying to figure out how to lock (and unlock) a loan in C#

### ISSUE THREAD

**Issue by paulmoseley** [EncompassRest/EncompassRest#340]
Hey there everyone!  New user here.  I think I've figured out how to get and update a loan, but I'm having trouble figuring out how to lock and unlock a loan around the update, I can't figure out how to get to the methods in the EncompassRest.Loan.LoanAPIs area.  Any clues or sample code would be appreciated.  Thanks!

**Comment by TylerBrinkley** [comment]
Please see the example from the unit tests. https://github.com/EncompassRest/EncompassRest/blob/master/src/EncompassRest.Tests/ResourceLocksTest.cs#L24

**Comment by paulmoseley** [comment]
Thanks, Tyler.  Samples/examples would be in the unit tests, of course (*blush*)...
