### ISSUE TITLE
Return back response message somehow with BaseApiClient.PostAsync

### ISSUE THREAD

**Issue by chris-thompson-go** [EncompassRest/EncompassRest#350]
Would there be a way to get to the response headers with BaseApiClient.PostAsync?  an api call return value is in the header.  I have  a case where I wanted to drop down to BaseApiClient and wanted to use that instead of dropping down to HttpClient mainly because I am leveraging the ApiResponse event.

**Comment by TylerBrinkley** [comment]
Not currently I'm afraid, though you can get it through the `ApiResponse` event. I'm open to suggestions as how to expose that information though.
