### ISSUE TITLE
URLA 2020

### ISSUE THREAD

**Issue by scmahaffey** [EncompassRest/EncompassRest#357]
It is unclear whether there has been an update to support new fields EM has created to handle new URLA 2020 requirements.

**Comment by rbpeterson2** [comment]
See release notes: https://docs.developer.elliemae.com/reference#section-august-20-1-service-pack

**Comment by scmahaffey** [comment]
The release notes non developer connect tell me about the Ellie Mae changes. My question is whether Encompass Rest library has been updated to support these changes. Am I missing how this page can clarify that question?

**Comment by ourialkada** [comment]
I have issues with this also. Is EncompassRest updated to support URLA Changes?

**Comment by ourialkada** [comment]
> The release notes non developer connect tell me about the Ellie Mae changes. My question is whether Encompass Rest library has been updated to support these changes. Am I missing how this page can clarify that question?

Did you figure anything out for this?

**Comment by TylerBrinkley** [comment]
I'm planning to make a nuget release by the end of the week which will include support for the new URLA fields.

**Comment by scmahaffey** [comment]
Thanks for answering my query and the notification!

Regards,

Sam

**Comment by ourialkada** [comment]
> I'm planning to make a nuget release by the end of the week which will include support for the new URLA fields.

Had the new nuget package been released? If not what is the timeframe which you think it will be released?

**Comment by TylerBrinkley** [comment]
It has not. The plan was to release it last weekend but I've got just a few more changes that need to be merged. I'd like to deploy at latest Wednesday. Sorry for the delay.

**Comment by TylerBrinkley** [comment]
Support for the URLA fields has been released in v1.3.0
