### ISSUE TITLE
Library is unable to authenticate

### ISSUE THREAD

**Issue by Oxymoron290** [EncompassRest/EncompassRest#360]
Our client secret has a number of percent symbols in it and it appears to be URL encoded already as it's %25 and %26 peppered throughout our client secret. The problem is that this library is unable to authenticate using our client secret due to [this line of code](https://github.com/EncompassRest/EncompassRest/blob/master/src/EncompassRest/Token/AccessToken.cs#L79).
https://github.com/EncompassRest/EncompassRest/blob/master/src/EncompassRest/Token/AccessToken.cs#L79

It appears that all percent symbols are arbitrarily filtered out and replaced with `%25`.

`_apiClientSecret.Replace("%", "%25")}")`

I'm reaching out to see what the motivation was behind doing this, discover is there is a different solution to that challenge, and request that the `.Replace` be removed from this line of code.

**Comment by TylerBrinkley** [comment]
The Replace method was added instead of a full URLEncode in #289. Did Ellie Mae provide you those client secrets like that? Perhaps we could add an additional `.Replace("%25", "%").Replace("%26", "?")` before replacing just `%`?

**Comment by Oxymoron290** [comment]
Based on your feedback I was wondering if my secret had already been encoded. I decoded my secret and plugged that into this library and it worked as designed. I'm closing this issue and my PR.

**Comment by TylerBrinkley** [comment]
Glad it worked for you!
