### ISSUE TITLE
URLA FIELDS ARE NOT FOUND 

### ISSUE THREAD

**Issue by ourialkada** [EncompassRest/EncompassRest#362]
When trying to find fields For example
loan.Fields["URLA.X265"].Value

the error is that the field URLA.X265 is not found. 

Is the issue on the EncompassRest side that it is not updated for the new URLA fields? or is this another issue?

If I use the API ({{API_SERVER}}/encompass/v1/loans/{{loanGuid}}/fieldReader) to get field value I get the new  fields

**Comment by TylerBrinkley** [comment]
Support for the URLA fields has been released in v1.3.0
