### ISSUE TITLE
Unable to define custom signingkey for webhook subscriptions

### ISSUE THREAD

**Issue by Oxymoron290** [EncompassRest/EncompassRest#363]
While creating a new webhook subscription, if no signing key is defined, then "the Encompass platform generates a default signing key." Based on my testing, this "default signing key" is the same and is not randomly generated with each new subscription. So we set out to define our own signing key using this library. The payload sent to encompass was the following:

```
POST https://api.elliemae.com/webhook/v1/subscriptions HTTP/1.1
Host: api.elliemae.com
Authorization: Bearer [REDACTED]
Content-Type: application/json
Content-Length: 195

{"events":["create","move","submit","update"],"endpoint":"https://www.bogus-endpoint-that-doesnt-exist-456knj.com/api/loan","signingKey":"thisisaSUPER1ongpasswordthatis!random","resource":"Loan"}
```

We ensured that the signing key was valid based on the encompass platform documentation, however we were unable to get any other signing key than the static default singing key from the encompass platform. No errors were indicated in the response message, which was as follows:

```
HTTP/1.1 201 Created
Date: Wed, 20 Jan 2021 21:47:18 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 34
Connection: keep-alive
Vary: X-HTTP-Method-Override, Accept-Encoding
Location: /webhook/v1/subscriptions/[RANDOM GUID]
X-Concurrency-Limit-Limit: 30
X-Concurrency-Limit-Remaining: 30
X-Rate-Limit-Limit: 500000
X-Rate-Limit-Remaining: 500000
X-Rate-Limit-Reset: 1611187200
.
.
.
Referrer-Policy: no-referrer
Expect-CT: max-age=86400, report-uri="/report"
X-Correlation-ID: [RANDOM GUID]

{"message":"Subscription created"}
```

After close inspection of the documentation, the property in the request payload `signingkey` is ALWAYS referenced as all lowercase, however the request being sent out by this library camel cases the property. As a test I sent an almost exact copy of the request generated by this library but changed that property name to reflect the documentation and the signing key was set on the encompass platform as expected.

I'm submitting this as an issue to see about serializing the Webhook.Subscription class with that property as all lowercase.

**Comment by TylerBrinkley** [comment]
Closed in #364. Thanks for bringing this to our attention and providing a PR fix.
