### ISSUE TITLE
Using Custom Fields in Filters

### ISSUE THREAD

**Issue by walkeryan** [EncompassRest/EncompassRest#37]
Is this possible using the API? I would assume so, but I'm getting 400 Status Bad request?

var filter = new StringFieldFilter("CX.CDS", StringFieldMatchType.Exact, "JD1024");

Thanks

**Comment by TylerBrinkley** [comment]
You need to specify the field id as "Fields.CX.CDS" just like the SDK requires.

**Comment by walkeryan** [comment]
I realized that just after I posted this, thanks for the quick response and
keep up the good work!
