### ISSUE TITLE
Set Rate Lock values by field ID, or the ability to clone a rate lock and change values

### ISSUE THREAD

**Issue by TimH-SL** [EncompassRest/EncompassRest#372]
In the SDK you had the ability to set virtual fields pertaining to the last rate lock.  For example, to set the "Investor Commitment Number" you would set field "LOCKRATE.2286" on a loan.  

If you attempt to set that field in EncompassRest, it is listed as a virtual field and it fails.

If I try "UpdateRateLockRequestAsync" I get "Rate lock cannot be updated since it is Locked."  

It seems that LOCKRATE.2286 pertains to "InvestorCommitment" on a rate lock in EncompassRest.  If I wanted to clone a rate lock and set just that value, how would I do it?  Attempts to use the returned rate lock object, changing the InvestorCommitment value, and submitting under the "SubmitRateLockRequestAsync" method have failed with the error: "Two out of Lock Date, Lock Number of Days or Lock Expiration Date properties are required."

Are there any other ways to set the LOCKRATE.2286 values using the API?

**Comment by mikecowgill** [comment]
I believe the key is to set the LockView.Detailed to get all the lock data back before reconfirming the lock. This is how I've used the API to update other Sell Side data.

```csharp
// Get the current lock
var currentLock = await loan.LoanApis.RateLocks.GetRateLockAsync(lockedRequest.Guid, LockView.Detailed);
currentLock.InvestorCommitment = "TEST_COMMITMENT";
await loan.LoanApis.RateLocks.SubmitRateLockRequestAsync(currentLock, true, LockAction.Confirm);
```

**Comment by TimH-SL** [comment]
> I believe the key is to set the LockView.Detailed to get all the lock data back before reconfirming the lock. This is how I've used the API to update other Sell Side data.
> 
> ```cs
> // Get the current lock
> var currentLock = await loan.LoanApis.RateLocks.GetRateLockAsync(lockedRequest.Guid, LockView.Detailed);
> currentLock.InvestorCommitment = "TEST_COMMITMENT";
> await loan.LoanApis.RateLocks.SubmitRateLockRequestAsync(currentLock, true, LockAction.Confirm);
> ```

Thank you Mike.  That did make a difference in being able to clone the lock.  That is very helpful!

However, for some reason it's still not updating the value.  We have Encompass Build 21.1.0.0.  I did exactly as you said and it is creating a clone of the old lock however when I check the value in the newly-created lock, it's no different.

What version of Encompass are you using?  Perhaps it's a bug in the new build.  This does work using the SDK, which is what we ended up having to use for now until we can get this working in EncompassRest.

![rate lock example 1](https://user-images.githubusercontent.com/73543287/107788813-7552c980-6d16-11eb-92d7-9cfbb81c68aa.png)

![rate lock example 2](https://user-images.githubusercontent.com/73543287/107788833-7ab01400-6d16-11eb-9f33-930438d56ce5.png)

![rate lock example 3](https://user-images.githubusercontent.com/73543287/107788851-7dab0480-6d16-11eb-86ae-4a6ea7c779bc.png)

**Comment by mikecowgill** [comment]
The Rate Lock API has been very inconsistent is which values it will update and what it doesn't. I think we all need to submit tickets to try to get this resolved.

Give this is a try to see if it at least gets the Investor commitment into the sell side investor data.

```csharp
var currentLock = await loan.LoanApis.RateLocks.GetRateLockAsync(lockedRequest.Guid, LockView.Detailed);
currentLock.InvestorCommitment = "currentLock.InvestorCommitment";
currentLock.BuySide.CommitmentNumber = "currentLock.BuySide.CommitmentNumber";
currentLock.SellSide.Investor = currentLock.SellSide.Investor ?? new Investor();
currentLock.SellSide.Investor.Commitment = "currentLock.SellSide.Investor.Commitment";
currentLock.SellSide.ServicingType = ServicingType.ServiceReleased;
currentLock.SellSide.Investor.LockType = CommitmentType.Mandatory;
```

In my case, I've been setting the currentLock.SellSide.ServicingType and currentLock.SellSide.Investor.LockType using this api and it was saving correctly. It also looks like the currentLock.SellSide.Investor.Commitment is as well, but I don't see that currentLock.SellSide.Investor.Commitment being copied into the main currentLock.InvestorCommitment. The rate lock api documentation doesn't really help much to figure out which field goes where in the Encompass UI.

I've just had to run experiments to discover what to use (and see what's broken)

**Comment by mikecowgill** [comment]
> What version of Encompass are you using? Perhaps it's a bug in the new build. This does work using the SDK, which is what we ended up having to use for now until we can get this working in EncompassRest.
> 

Oh, and the encompass server I'm on is currently 21.0.0.0 as well.

**Comment by TimH-SL** [comment]
Thanks Mike.  I'm glad you're using the same version of Encompass as us.  I think I understand it better now.

The SDK will update a locked/confirmed rate lock but not update the loan (we update field LOCKRATE.2286 for this in the SDK).  So, the next time you create a new rate lock in Encompass, it won't use the values you set in the prior rate lock.  I'm not sure that that is what people want since ultimately it is manipulating snapshot data for a confirmed rate lock that way, since it doesn't create a new rate lock and just updates the one that is there.

I looked at the documentation for the API request: https://docs.developer.elliemae.com/reference#submit-a-rate-lock-request

And I looked at the API calls from EncompassRest.  When I set "rateLock.InvestorCommitment" in the code, it set the following value:

{
    "investorCommitment": "5554444"
}

I have no idea what that does, but I couldn't find that value anywhere in the GUI.  Not only did it not set the value for the loan so new rate locks created in Encompass would have it, it didn't update the rate lock as I showed before.

However, the following two approaches work.  They do however set the value in the loan so the next time you create a new rate lock, it'll use those values.

                loan.Fields["2286"].Value = "1234567";
                await client.Loans.UpdateLoanAsync(loan);
                await loan.LoanApis.RateLocks.SubmitRateLockRequestAsync(rateLock, true, LockAction.Confirm);

This sets the value directly in the loan, then creates a new rate lock which pulls in the updated values.  When you create a new rate lock in Encompass, it'll use the new value from the loan.

                rateLock.SellSide.Investor.Commitment = "654321";
                await loan.LoanApis.RateLocks.SubmitRateLockRequestAsync(rateLock, true, LockAction.Confirm);

This ironically seems to accomplish the same thing, although through a different API call.  It updates the value directly in the loan because after I do this, the value 654321 is on sell side investor commitment in Encompass when I try to create a new rate lock within the GUI.

The json looks similar to this for that call:

{
    "sellSide": {
        "investor": {
            "commitment": "55533344"
        }
    }
}

So it looks like either of these two approaches will update that value, although it doesn't update the prior confirmed rate lock snapshot like what the SDK allows.

**Comment by TimH-SL** [comment]
Just one more comment.  It looks like some of the fields are read only on a loan, so you can't set them through the loan.  For example, field ID 2246 is "Rate Lock Sell Side Base Price Adjust 7 Rate".  If you try to set that on the loan directly (loan.Fields["2246"].Value) it fails and says that it is read only.  I don't know if you could try to set it directly on the rate lock adjustment itself, but I assume you can.

**Comment by TylerBrinkley** [comment]
`EncompassRest` will let you set read-only fields locally if you set the `LoanFields.AllowWritesToReadOnlyFieldsLocally` to `true`.

See here for an example from the unit tests.
https://github.com/EncompassRest/EncompassRest/blob/ed5da291a84bbcf63d72de3ef1f3aabd67b51b8f/src/EncompassRest.Tests/LoanTests.cs#L2141-L2162

**Comment by TimH-SL** [comment]
I had tried that before with the virtual fields and the loan failed to update.  So, I didn't even think of trying it again now.

I just tried it and it worked fine.  The fields are 2243, 2244, 2245, 2246, 2247, and 2248 and they all updated as long as I set AllowWritesToReadOnlyFieldsLocally to true.

Thank you Tyler!
