### ISSUE TITLE
Loan Template

### ISSUE THREAD

**Issue by alfredovel** [EncompassRest/EncompassRest#38]
In SDK, we can pull a loan template and apply this template when creating a new loan.  Is this available in REST?  Thank you

**Comment by TylerBrinkley** [comment]
It's not currently exposed by the Encompass API's but is scheduled to be released Nov 11, tentatively.

**Comment by alfredovel** [comment]
Thank you

**Comment by TylerBrinkley** [comment]
We will then have to add the feature to EncompassRest after the API is exposed.

**Comment by hfcjweinstock** [comment]
this looks to be coming 11/18

**Comment by hfcjweinstock** [comment]
this will be resolved with #62
