### ISSUE TITLE
Can't upload Attachments to eFolder using current AttachmentType parameter

### ISSUE THREAD

**Issue by UT-BrandonBauer** [EncompassRest/EncompassRest#382]
It seems like Ellie Mae may have changed the way the AttachmentType found in EncompassRest.Loans.Attachments  functions / is setup. Utilizing the current EncompassRest when trying to make an upload, I get an the following: `"Invalid content for parameter 'attachmentType' in request."` while utilizing EncompassRest.
 
From what I understand, Ellie's latest update apparently changed the AttachmentType parameter from an int to a string in the LoanAttachment object. A co-worker of mine stated they know someone at another company who resolved this issue for their company by changing the AttachmentType to pass "Native" instead of the int zero. 
 
Since EncompassRest is doing creating an AttachmentType as an enum / int, it’s likely not meeting the new requirements Ellie Mae currently has set and gives that error I have above. I’m not sure if Ellie Mae intentionally did this, but I do know that it is affecting stuff as a result of it, so I wanted to report the problem to you in case it is a legit issue.

**Comment by shawnfultz** [comment]
I'm having this issue across many different encompass smart client id's. The update over the weekend broke this.

Error: GetUploadAttachmentUrlAsync: 687c0070-9747-4901-9161-90badcd0668d - 400: BadRequest - CorrelationId: 920dd199-1ec1-4db6-b97e-e4415eaa9947
{"code":"EFOLDER-2001","summary":"Bad Request","details":"Invalid content for parameter 'attachmentType' in request."}. Stack Trace:    at EncompassRest.ApiObject.<SendFullUriAsync>d__42`1.MoveNext()

**Comment by shawnfultz** [comment]
Quick update. If you're taking the upload response and passing it to the GetAttachments, just comment out the AttachmentType or don't set it. You can omit the AttachmentType from the GetAttachments and it won't throw.

![image](https://user-images.githubusercontent.com/1320217/114472782-ee5c8900-9bc0-11eb-9007-63da9967d515.png)

**Comment by mtucker6784** [comment]
Thanks for the information, @shawnfultz , we are seeing this popup as well in our environment as of today.

**Comment by UT-BrandonBauer** [comment]
I tried commenting out / setting AttachmentType as null before trying to run the `UploadAttachmentAsync()` which does seem to allow it to move past the initial call of `GetUploadAttachmentUrlInternalAsync()` to generate a media url. However, during the second call of `SendFullUriPopulateDirtyAsync()` when trying actually post the data and metadata to that URL for the actual upload of the data, it ends up failing with an 401 / access denied / unauthorized error with a message of `"UploadAttachmentAsync: 4fccca1a-714b-4d73-b787-95393a5601fc\r\n"`


| Response | {StatusCode: 401, ReasonPhrase: '', Version: 1.1, Content: System.Net.Http.StreamContent, Headers: {   Pragma: no-cache   X-Correlation-ID: 71aa311a-7dde-4d57-9c16-957c8ffae9ff   X-Correlation-ID: 71aa311a-7dde-4d57-9c16-957c8ffae9ff   CorrelationID: 71aa311a-7dde-4d57-9c16-957c8ffae9ff   Access-Control-Request-Headers: Authorization   Access-Control-Allow-Headers: Elli-Session, Authorization, Origin, Content-Type, Accept   Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS   Access-Control-Allow-Origin: *   Access-Control-Max-Age: 1800   Cache-Control: no-cache   Date: Tue, 13 Apr 2021 01:43:35 GMT   Server: Microsoft-IIS/8.5   WWW-Authenticate: Bearer   X-AspNet-Version: 4.0.30319   X-Powered-By: ASP.NET   Content-Length: 0   Allow: GET   Allow: POST   Allow: PUT   Allow: DELETE   Allow: OPTIONS   Expires: -1 }} | System.Net.Http.HttpResponseMessage

{Method: PUT, RequestUri: 'https://media-pod1-ep3.elliemae.com/v2/media/instance/TEBE11173166/loans/4fccca1a-714b-4d73-b787-95393a5601fc/files/attachment-c61cbb7e-9e22-4b79-98a0-0c4087c9c0b3.txt?endpoint=aHR0cHM6Ly9lZm9sZGVyb3JjaGVzdHJhdGlvbi5lbGxpZXNlcnZpY2VzLmNvbS92MS9jYWxsYmFja3MvbWVkaWFBdHRhY2htZW50cw%253D%253D&data=eyJ0aXRsZSI6IlRlc3RpbmcgQXR0YWNobWVudCIsImF0dGFjaG1lbnRJZCI6ImF0dGFjaG1lbnQtYzYxY2JiN2UtOWUyMi00Yjc5LTk4YTAtMGM0MDg3YzljMGIzLnR4dCIsImRhdGVDcmVhdGVkIjoiMjAyMS0wNC0xM1QwMTo0MzozMi41MDhaIiwiY3JlYXRlZEJ5Ijoib2FwaSIsImNyZWF0ZVJlYXNvbiI6MSwiYXR0YWNobWVudFR5cGUiOiJOYXRpdmUiLCJlYnNQb2RVcmwiOiJodHRwczovL2VuY3BsYXQtcG9kdHYyMTEuZXAzLmRjby5lbG1hZSIsImxvYW5JZCI6IjRmY2NjYTFhLTcxNGItNGQ3My1iNzg3LTk1MzkzYTU2MDFmYyIsImNsaWVudElkIjoiMzAxMTE3MzE2NiIsImNvbnRlbnRUeXBlIjoidGV4dC9wbGFpbiIsImZpbGVLZXkiOiJhdHRhY2htZW50LWM2MWNiYjdlLTllMjItNGI3OS05OGEwLTBjNDA4N2M5YzBiMy50eHQiLCJ2aWV3IjoiZW50aXR5Iiwia2VlcE9yaWdpbmFsQ29weSI6ZmFsc2UsInYxQ3JlYXRlQXR0YWNobWVudCI6dHJ1ZX0%253D&tokencreator=efolder&tokenexpires=1618279112&token=cEqE6kTkRqctSR1IyZ9VUTbp2wtSYUc5QqGKf5YB%2bZvSEq%2f%2fI4r2zI4thmX1aW2WaJcDGiWLPZNmvY4liODc4Q%3d%3d', Version: 1.1, Content: System.Net.Http.ByteArrayContent, Headers:
{
  x-api-key: 9JsmcmHyzJuokoWeJJ8HGiRgS5GR8cSKVswz
  origin: 
  Content-Length: 25
}}

**Comment by TylerBrinkley** [comment]
We can easily push a fix to change `AttachmentType` to be a `string` or `StringEnumValue<AttachmentType>` but I'm also getting the 401 errors in the integration tests. Can you all create support tickets into ICE regarding that error?

**Comment by mtucker6784** [comment]
@TylerBrinkley  yessir, can do

**Comment by mtucker6784** [comment]
Response from ICE

![image](https://user-images.githubusercontent.com/1609106/114649493-7a3fe500-9c95-11eb-8b9c-46f2e0e854c7.png)

**Comment by TylerBrinkley** [comment]
Thanks for the update.

**Comment by UT-BrandonBauer** [comment]
![image](https://user-images.githubusercontent.com/28020760/114714773-6bdae300-9d00-11eb-82d3-70bc8a1d6c6c.png)
It appears the EncompassRest unit test gets passed the 401 error now, so I believe Ellie Mae has resolved the 401 issue. @TylerBrinkley

**Comment by TylerBrinkley** [comment]
Thanks @UT-BrandonBauer for the heads up. I've created a PR to switch the `AttachmentType` to a `StringEnumValue<AttachmentType>`.

**Comment by TylerBrinkley** [comment]
EncompassRest v1.3.2 has been pushed out to fix this issue.
