### ISSUE TITLE
Loan Batch update

### ISSUE THREAD

**Issue by walkeryan** [EncompassRest/EncompassRest#39]
I'm trying to update 10 Fields on several thousand loans. I figured using BatchUpdate.UpdateLoansAsync would work but the BatchUpdateParameters object only seems to take a List of GUID's and a List of FieldValuePairs. I've looked at the code but I'm not familiar enough to figure out what its doing. Can I pass in a list of loan GUID's with a List of FieldValuePairs List (Separate for each loan)? Or does it update every loan with the same FieldValuesPairs passed in?

**Comment by TylerBrinkley** [comment]
It updates every loan specified with the same FieldValuePairs. If you need the fields to be different on a loan by loan basis then you should make multiple calls to `BatchUpdate.UpdateLoansAsync`.

**Comment by TylerBrinkley** [comment]
@walkeryan for these support type questions perhaps it would be best to post them on the Slack group. Here's a link to the Ellie Mae forums with how to join the Slack group. http://forum.elliemae.com/index.php?/topic/6099-slack-channel-for-encompass-devs-join-us/

**Comment by walkeryan** [comment]
Thanks Tyler, I sent him an e-mail.
