### ISSUE TITLE
UploadAttachmentAsync throwing 400 during PUT request

### ISSUE THREAD

**Issue by rydonjs** [EncompassRest/EncompassRest#393]
Hello fellow devs!

We have an app that uses the EncompassRest library to upload documents to Encompass for a specified loan. In order to accomplish this we utilize the UploadAttachmentAsync(...) method by passing in the LoanAttachment object and the fileContent byte array as parameters. This method has been working as expected until about a week ago, when it suddenly started throwing 400 (see attachment). The code leading up to this call has not had significant changes for a few weeks, so I can't narrow down a specific area of code that may have caused this. This leads me to believe the underlying Ellie Mae API may have been updated and, in turn, this method may need to be updated.

Here are the exception details:

Message:
Message = "UploadAttachmentAsync: fa7fc022-cdd3-4f7a-98b1-46d042ea61e6 - 400: BadRequest - CorrelationId: d72918e8-eafb-41ab-9999-94452c90267f\r\n{\"code\":\"SKYDRIVESTREAM-3003\",\"summary\":\"Bad Request\",\"details\":\"Following header must be present :  'contentT...

Response:
Response = {StatusCode: 400, ReasonPhrase: '', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Transfer-Encoding: chunked
  Connection: keep-alive
  Access-Control-Allow-Origin: *
  Access-Control-Allow-Methods: POST, GET, PUT, OPTIONS, DELETE
...

Response Content:
ResponseContent = "{\"code\":\"SKYDRIVESTREAM-3003\",\"summary\":\"Bad Request\",\"details\":\"Following header must be present :  'contentType'\"}"

Any help is much appreciated!

![github-1](https://user-images.githubusercontent.com/28198592/122470936-a7a65900-cf8c-11eb-893f-d1b3337c1021.png)
![github-2](https://user-images.githubusercontent.com/28198592/122470939-a8d78600-cf8c-11eb-9f77-81352fbd99a5.png)
![github-3](https://user-images.githubusercontent.com/28198592/122470940-a8d78600-cf8c-11eb-8871-d3d881d73738.png)

**Comment by TylerBrinkley** [comment]
It looks like we need to send a content-type header to that PUT call. I wonder if `application/octet-stream` is the correct content-type to send?

**Comment by rydonjs** [comment]
@TylerBrinkley I'm not sure. I know in this particular case I was attempting to sync a PDF, so would the content type need to be passed in with each call, ex: application/pdf. Or is there a content type that works for all document types?

**Comment by rydonjs** [comment]
@TylerBrinkley Where can I find the documentation for the UploadAttachmentAsync(...) method, for some reason I can't seem to find it on the github. Also is there anything else I can provide to help troubleshoot the issue?

**Comment by TylerBrinkley** [comment]
Here's a link to the code. https://github.com/EncompassRest/EncompassRest/blob/60e4b9dcab92a40dfc3486ef40faff537c23ca15/src/EncompassRest/Loans/Attachments/LoanAttachments.cs#L329-L337

Here's a link to the Developer Connect documentation. https://docs.developer.elliemae.com/reference#upload-attachment-to-efolder

I'm thinking I'm going to need to get the file extension and set the content-type based on that and fall back to `application/octet-stream` if I can't determine the content-type. Right now when running the unit tests I'm getting an error trying to retrieve an attachment url.

**Comment by mtucker6784** [comment]
Hey all! Have there been any updates on this? I'm seeing this same error in my log files as well. It seems to be hit and miss, but it's weird because everything we're uploading via the EncRest library is a PDF file.

Here's an example of where it passes, but then the next loan object it fails on:

```
2021-07-08 14:25:08,586 [11] INFO UploadEFolderAttachment.EFolderAttachment - Successfully moved the uploaded file to the "Lock Confirmation" document.
2021-07-08 14:28:18,187 [1] INFO UploadEFolderAttachment.EFolderAttachment - Beginning eFolder attachment process.
2021-07-08 14:28:28,229 [4] FATAL UploadEFolderAttachment.EFolderAttachment - Unable to upload document! ExMsg: UploadAttachmentAsync: d6aed63a-dbad-497d-bbef-2cf8102f7174 - 400: BadRequest - CorrelationId: 810c49b0-00a9-43ed-b520-d574b650cd86
{"code":"SKYDRIVESTREAM-3003","summary":"Bad Request","details":"Following header must be present :  'contentType'"}    at EncompassRest.ApiObject.<SendFullUriAsync>d__44`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EncompassRest.Loans.Attachments.LoanAttachments.<UploadAttachmentAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at UploadEFolderAttachment.EFolderAttachment.<AttachToEFolderAsync>d__6.MoveNext() in C:\GitHubRepos\NDMWebAPI\UploadEFolderAttachment\EFolderAttachment.cs:line 76
```

**Comment by rydonjs** [comment]
@mtucker6784 - In my case, the issue was that when making the UploadAttachmentAsync call, the content type was not being set in the request's header. To resolve this, we replaced the UploadAttachmentAsync(...) with two separate calls:

1. First use GetUploadAttachmentUrlAsync(...) to get the media url
2. Make a put PUT call to that url and specify the content type in the header based on the file type

See attached screen shot.

![UploadAttachment-SpecifyContentType](https://user-images.githubusercontent.com/28198592/124995722-c345d200-e015-11eb-8fee-7ceea1a624bb.png)

**Comment by mtucker6784** [comment]
Awesome, thank you @rydonjs, much appreciated!
