### ISSUE TITLE
Attachments - Question about /v1 or /v2 responses

### ISSUE THREAD

**Issue by mtucker6784** [EncompassRest/EncompassRest#394]
I've a question, hopefully someone can point me in the right direction.

I started experiencing content-Type errors about a week and some odd change ago, which I piggy backed off of #393 . The solution seemed to be replacing the library's UploadAttachmentAsync() with 2 different calls. That seems to work OK if I get a response from /v2, but if I get a response from /v1, then I'm having problems.

With that said, what determines if the response will come from `https://media-podX-epX.elliemae.com/**v2/**...` vs `https://streaming.us-<direction>.skydrive.ellieservices.com/**v1/**...` ?

This is using EncRest 1.32, I understand that even the Developer connect docs explicitly say **/v1** but it doesn't make sense why I get **/v2** responses on some files. The loans are similar, and everything we upload is strictly in PDF format.

If I get a response from **/v2**, I'm able to successfully use   ```loan.LoanApis.Documents.AssignDocumentAttachmentsAsync(containerId, AssignmentAction.Add,
                    new List<EntityReference>() { new EntityReference(attachId, EntityType.Attachment) });```

I'm able to get the `attachId` by parsing the response property return like this:
```
            var response = await client.BaseApiClient.HttpClient.SendAsync(request, HttpCompletionOption.ResponseContentRead);
            string respPath = response.RequestMessage.RequestUri.LocalPath;
            var respGetAttId = respPath.Split('/');
            string attachId = respGetAttId[8].Substring(11, respGetAttId[8].Length - 15);
```

However, that doesn't carry over if I get a return from **/v1**.

If I just use:
```

            var request = new HttpRequestMessage(new HttpMethod("PUT"), mediaUrl.MediaUrl)
            {
                Content = new ByteArrayContent(fileBytes)
            };
            var mediaType = "application/pdf";
            request.Content.Headers.ContentType = new MediaTypeHeaderValue(mediaType);
            var response = await client.BaseApiClient.HttpClient.SendAsync(request, HttpCompletionOption.ResponseContentRead);

```
and get a **/v1** response, then I do get a successful status code, but the PDF does not show up in the loan object's efolder. I assume it's because I'm not actually telling EncompassRest to explicitly put the document in the efolder, but part of me feels like using `await client.BaseApiClient.HttpClient.SendAsync(...)` should push the PDF to the efolder, even if not inside a container.

Am I missing something? I'll post screenshots of when I'm seeing /v1 and /v2 returns on PDF files. Yes, they are different loans, however the loans were both created this week. The loan programs Are different, but I'm not entirely sure if that would be the **exact** cause of the discrepancy I'm seeing.

Thank you.

![image](https://user-images.githubusercontent.com/1609106/125825174-5dfbe3c6-02da-475c-9513-9efb65c7b5ed.png)

![image](https://user-images.githubusercontent.com/1609106/125825191-2b30a637-90ef-4364-b1eb-145713c41bc1.png)

edit: There are some loans that do have the same loan program but exhibit the quirks I listed above.

**Comment by mtucker6784** [comment]
I will close this issue out. I modified the EncRest source code and solved the problems we were having with the contentType missing in the request. I can now use the following 2 original lines that we were using originally to upload and assign the document to a container.

`LoanApis.Attachments.UploadAttachmentAsync(...);`

and can now reassign the document to the right container using:

```
LoanApis.Documents.AssignDocumentAttachmentsAsync(ContainerIDStringHere, AssignmentAction.Add,
new List<EntityReference>() { new EntityReference(attachIdStringHere, EntityType.Attachment) });
```

**Comment by rydonjs** [comment]
Thanks for this write-up and resolution. It's extremely helpful!
