### ISSUE TITLE
Raw methods query parameters

### ISSUE THREAD

**Issue by TylerBrinkley** [EncompassRest/EncompassRest#43]
It seems to me that the raw methods' query parameters should be a string parameter instead of using the objects in the non raw methods. This way users can easily add more query parameters when Ellie Mae adds them without having to wait for us and the users are entirely in control of what's being sent. Thoughts?

**Comment by hfcjweinstock** [comment]
i think maybe have it as an override?

**Comment by TylerBrinkley** [comment]
Sounds good to me
