### ISSUE TITLE
Add ExtensionData Support

### ISSUE THREAD

**Issue by TylerBrinkley** [EncompassRest/EncompassRest#50]
Currently when our POCO's don't specify a property that is in the json, it is discarded. I think we should expose an `ExtensionData` property to all classes for when users need a property not currently defined in the POCO's but would still like to use the POCO's instead of the raw methods.

## Example Implementation
```c#
public sealed class Loan
{
    private DirtyDictionary<string, object> _extensionData;
    [JsonExtensionData]
    public IDictionary<string, object> ExtensionData { get { return _extensionData ?? (_extensionData = new DirtyDictionary()); } set { _extensionData = new DirtyDictionary(value); } }
}

internal sealed class DirtyDictionary<TKey, TValue> : IDictionary<TKey, TValue>, IDirty
{
    ...
}
```

**Comment by hfcjweinstock** [comment]
i am of 2 minds. should we wait for the new values to be properly imported to the Project so they can be properly implemented?  should implement this value for all objects for the same issue?

**Comment by TylerBrinkley** [comment]
This feature is for when the API is updated later and users want to use something that we haven't updated the library for yet. An example would be the `Loan.VirtualFields` which we can't currently get the schema for yet.
