### ISSUE TITLE
Serialize dates without time

### ISSUE THREAD

**Issue by TylerBrinkley** [EncompassRest/EncompassRest#56]
We should add support to serialize dates without the time component.

**Comment by hfcjweinstock** [comment]
we need to be VERY careful with this.  just because ellie does not currently store time in all date/time objects, doesnt mean we shouldnt.

**Comment by TylerBrinkley** [comment]
In the schema there is both a date and datetime type. I just propose we configure serialization of those date types to only serialize the date portion through an attribute but we'd still use `System.DateTime`. We can always update the library later to output the time component without breaking the public interface. We'd just need to make sure that we accept datetime formatted json when deserializing to the date types.

**Comment by TylerBrinkley** [comment]
I was originally under the impression that this is what Ellie Mae does when sending dates back in the Loan object but that is not the case. I'm going to close this as I was mostly just trying to match Ellie Mae's output.
