### ISSUE TITLE
Efolder Enhancement - Upload attachment

### ISSUE THREAD

**Issue by hfcjweinstock** [EncompassRest/EncompassRest#64]
The eFolder: Attachments API includes operations to upload attachments to the eFolder

**Comment by hfcjweinstock** [comment]
would you be willing to build it out in the system and submit a pull?

**Comment by TylerBrinkley** [comment]
Please post your public API additions in this issue first and adjust it as necessary when prototyping it.

**Comment by arhoads76** [comment]
Unless I'm missing something in the code, we probably first need methods to create an Attachment and create a LoanAttachment reference.  Once we have those, a convenience method that combined those two steps would make sense in the LoanDocuments class.  I'd probably name it something like AddAttachment().

**Comment by TylerBrinkley** [comment]
I think we would add a method to the `LoanAttachments` class with the attachment info and data which would make a call to https://api.elliemae.com/encompass/v1/loans/loanId/attachments/url and then immediately make another call to the returned url to upload the attachment.

**Comment by hfcjweinstock** [comment]
This is the first time we must be careful about throwing proper exceptions.  these functions may not only be REST Exceptions.

**Comment by TylerBrinkley** [comment]
## Proposed API
```diff
 namespace EncompassRest.Loans.Attachments {
     public class LoanAttachments {
+        public Task<string> UploadAttachmentAsync(LoanAttachment attachment, byte[] attachmentData, CancellationToken cancellationToken = default);
+        public Task<string> UploadAttachmentAsync(LoanAttachment attachment, byte[] attachmentData, bool populate, CancellationToken cancellationToken = default);
+        public Task<string> UploadAttachmentRawAsync(string attachment, byte[] attachmentData, CancellationToken cancellationToken = default);
+        public Task<string> UploadAttachmentRawAsync(string attachment, byte[] attachmentData, string queryString, CancellationToken cancellationToken = default);
+        public Task<byte[]> GetAttachmentDataAsync(string attachmentId, CancellationToken cancellationToken = default);
+        public Task<byte[]> GetAttachmentPageAsync(string attachmentId, string pageId, CancellationToken cancellationToken = default);
+        public Task<byte[]> GetAttachmentPageThumbnailAsync(string attachmentId, string pageId, CancellationToken cancellationToken = default);
-        public Task<AttachmentUrl> GetAttachmentUrlAsync(string attachmentId, CancellationToken cancellationToken = default);
-        public Task<string> GetAttachmentUrlRawAsync(string attachmentId, CancellationToken cancellationToken = default);
     }
-    public sealed class AttachmentUrl : ExtensibleObject {
-        public string MediaUrl { get; set; }
-    }
 }
```

I removed the url methods as they don't seem useful by themselves as they're just the first part of retrieving the attachment data and I don't want to add public methods for second part which retrieves or sends data to any url.

**Comment by hfcjweinstock** [comment]
as long as the URL is exposed in the Raw, i have no problem

**Comment by TylerBrinkley** [comment]
I'm not sure what you mean.

**Comment by hfcjweinstock** [comment]
GetAttachmentUrlRawAsync should still be exposed

**Comment by TylerBrinkley** [comment]
How would a user use the url returned from that method though? They would need to create their own `HttpClient` and make a call with that url. Is anyone going to do that?

**Comment by hfcjweinstock** [comment]
they may have another rest endpoint that can send a file to a URL.

**Comment by arhoads76** [comment]
Is the GetAttachmentDataAsync method working now (rather, the underlying rest endpoint)?  It seems that Encompass was throwing errors about being unable to find the file.

**Comment by TylerBrinkley** [comment]
@hfcjweinstock How does the proposed API look?

**Comment by hfcjweinstock** [comment]
2 things...is it possible to return a Stream for the download?
i still think the GetAttachmentUrlRawAsync should be included.

**Comment by TylerBrinkley** [comment]
I like the `Stream` idea but we'll need to make sure it doesn't get disposed before returning to the users.

I included the Url methods including non-raw ones but just renamed that one to `GetDownloadAttachmentUrlAsync`.

**Comment by hfcjweinstock** [comment]
ok.  agreed then. (is LoanAttachments a LoanApiObject?)

**Comment by arhoads76** [comment]
I am working on a spike, and I’m not sure the Encompass REST endpoint is functional.  When I call the POST v1/loans/{loanId/attachments/{attachmentId}/url endpoint (which is for retrieving the attachment URL!!) I get either an error about native format or I get a 404 (the documentation about what is expected for attachmentId is not particularly clear).  And I’m sure what endpoint I’m supposed to call when actually posting the attachment contents if POST is for retrieval.

Aaron

**Comment by TylerBrinkley** [comment]
To enable both `Stream` and `byte[]` what should be the naming? We have a few options.

A.
```c#
public Stream DownloadAttachmentAsync(string attachmentId, CancellationToken cancellationToken = default);
public byte[] DownloadAttachmentByteArrayAsync(string attachmentId, CancellationToken cancellationToken = default);
```

B.
```c#
public byte[] DownloadAttachmentAsync(string attachmentId, CancellationToken cancellationToken = default);
public Stream DownloadAttachmentStreamAsync(string attachmentId, CancellationToken cancellationToken = default);
```

C.
```c#
public Stream DownloadAttachmentStreamAsync(string attachmentId, CancellationToken cancellationToken = default);
public byte[] DownloadAttachmentByteArrayAsync(string attachmentId, CancellationToken cancellationToken = default);
```

**Comment by hfcjweinstock** [comment]
B.  Common convention is if returning a stream, have it part of the class name.

**Comment by hfcjweinstock** [comment]
@arhoads76 There were a number of bugs on the upload/download of attachments on the EllieMae side when this was first written.  They have mostly been addressed, and the updated functionality has not been fully implemented yet.

**Comment by arhoads76** [comment]
Can we implement the methods we’re discussing here if the EllieMae side is not functional?

**Comment by TylerBrinkley** [comment]
I've updated the proposal to include DownloadStream methods. Should we also have UploadStream methods?

**Comment by hfcjweinstock** [comment]
Ellie MAe is functional, ou just have to know a few things.  if the attachment is a "Converted" attachment you need to use the pages path

**Comment by TylerBrinkley** [comment]
@arhoads76 Thank you for contributing to the conversation here but in the future could you please reply directly on the site so as not to clutter the issue with email information? Thanks.

**Comment by hfcjweinstock** [comment]
@TylerBrinkley we may as well allow for stream uploads. i hate byte arrays, and if i can avoid the conversion, i will be happy.

**Comment by arhoads76** [comment]
I logged in to clean up the extra email stuff my posts, but I don't see that it is present. Did you already modify my posts to clean them up, or is it only showing up in the emails? I'm happy to reply on the site if it keeps the conversation thread looking better, GitHubs emails suggested replying directly to the email, so I did.

**Comment by arhoads76** [comment]
Quick test.  I’ll delete momentarily.

**Comment by arhoads76** [comment]
Second quick test. I’ll delete momentarily

**Comment by TylerBrinkley** [comment]
I already cleaned up your posts but thanks.

**Comment by arhoads76** [comment]
It looks like if I erase the body before replying by email it will be clean.

**Comment by TylerBrinkley** [comment]
Well that works too. Thanks.

**Comment by TylerBrinkley** [comment]
I've updated the proposal to include `Stream` support for uploads as well.

Is this not one of the longest method names you've ever come across?
`DownloadAttachmentPageThumbnailStreamAsync`

**Comment by hfcjweinstock** [comment]
There is a method called GetTextEffectCharacterIndexFromTextSourceCharacterIndex under System.Windows.Media.TextFormatting.TextSource

**Comment by hfcjweinstock** [comment]
i think this looks good.

**Comment by TylerBrinkley** [comment]
> There is a method called GetTextEffectCharacterIndexFromTextSourceCharacterIndex under System.Windows.Media.TextFormatting.TextSource

Wow!

Also, yes `LoanAttachments` is a `LoanApiObject`.
