### ISSUE TITLE
getLoanAsync - cannot pass string list for entities

### ISSUE THREAD

**Issue by hfcjweinstock** [EncompassRest/EncompassRest#68]
cannot convert from List<string> to List<StringEnumValue<LoanEntities>>

**Comment by TylerBrinkley** [comment]
Hmm, you can do this

```c#
await client.GetLoanAsync(loanId, "Loan", "Borrower", "Application");
```

or

```c#
await client.GetLoanAsync(loanId, new List<StringEnumValue<LoanEntity>> { "Loan", "Borrower", "Application" });
```

**Comment by TylerBrinkley** [comment]
I'm beginning to think we may need to remove the params overloads due to additions of future string query parameters.

**Comment by hfcjweinstock** [comment]
cant do this:
```c#
await client.GetLoanAsync(loanId, new List<string> { "Loan", "Borrower", "Application" });
```

**Comment by TylerBrinkley** [comment]
Is that really a big problem? If so we can remove the `IEnumerable<StringEnumValue<LoanEntity>>` overloads and replace them with `IEnumerable<string>` and `IEnumerable<LoanEntity>` overloads.

**Comment by TylerBrinkley** [comment]
I think it would be good to allow this so I'm going to remove uses of `StringEnumValue` for collection parameter inputs.

**Comment by TylerBrinkley** [comment]
How would you handle [Webhook.GetSubscriptionsAsync](https://github.com/EncompassRest/EncompassRest/blob/master/src/EncompassRest/Webhook/Webhook.cs#L117) without using `StringEnumValue` but still retaining use of the enums?

**Comment by hfcjweinstock** [comment]
i think it is just a matter of accepting a list<string> and converting it.

**Comment by TylerBrinkley** [comment]
A list of what?

**Comment by hfcjweinstock** [comment]
fixed comment.
