### ISSUE TITLE
Add ResourceLocks API handler

### ISSUE THREAD

**Issue by hfcjweinstock** [EncompassRest/EncompassRest#74]
add the new loan Resource locks API endpoint.

**Comment by hfcjweinstock** [comment]
these are "different" of course.

which makes more sense : 
`private async Task<ResourceLock> GetResourceLockAsync(string resourceId, string lockId, string resourceType, CancellationToken cancellationToken)`

`private async Task<ResourceLock> GetResourceLockAsync(ResourceLock resourceLock, CancellationToken cancellationToken)`

or abstracting Resource lock and making it resource level : (`Loan.GetLock`, `Loan.Lock`, etc)

or something else....i have been back and forth on this the way they are handling it is odd.

**Comment by hfcjweinstock** [comment]
Proposed Prototype
```c#
public sealed class ResourceLock : ExtensibleObject, IIdentifiable
    {
        public string Id { get; set; }
        public Resource Resource { get; set; }
        public string UserId { get; set; }
        public StringEnumValue<ResourceLockType> LockType { get; set; }
        public string LockTime { get; set; }

        [IdPropertyName(nameof(Id))]
        string IIdentifiable.Id { get => Id; set => Id = value; }
    }

    public sealed class Resource : ExtensibleObject, IIdentifiable
    {
        public string EntityId { get; set; }
        public StringEnumValue<ResourceEntityType> EntityType { get; set; }

        [IdPropertyName(nameof(EntityId))]
        string IIdentifiable.Id { get => EntityId; set => EntityId = value; }
    }
    public enum ResourceEntityType
    {
        Loan = 0
    }

    public enum ResourceLockType
    {
        Exclusive = 0,
        Shared = 1
    }

public sealed class ResourceLocks : ApiObject
    {
        internal ResourceLocks(EncompassRestClient client) : 
            base(client, "encompass/v1/resourceLocks")
        {
        }

public Task<ResourceLock> GetResourceLockAsync(ResourceLock resourceLock, CancellationToken cancellationToken = default);
public Task<ResourceLock> GetResourceLockAsync(string resourceId, string lockId,  CancellationToken cancellationToken = default);
public Task<ResourceLock> GetResourceLockAsync(string resourceId, string lockId, ResourceEntityType resourceType, CancellationToken cancellationToken = default);
private async Task<ResourceLock> GetResourceLockAsync(string resourceId, string lockId, string resourceType, CancellationToken cancellationToken = default);
public Task<List<ResourceLock>> GetResourceLocksAsync(string resourceId, CancellationToken cancellationToken = default);
private async Task<List<ResourceLock>> GetResourceLocksAsync(string resourceId, string resourceType,  CancellationToken cancellationToken = default);
public Task<string> LockResourceAsync(ResourceLock resource, CancellationToken cancellationToken = default);
public Task<string> LockResourceAsync(ResourceLock resource, bool force, CancellationToken cancellationToken = default);
public Task<string> LockResourceAsync(ResourceLock resourceLock, bool force, bool populate, CancellationToken cancellationToken = default);
public Task<bool> UnlockResourceAsync(string resourceId, string lockId, CancellationToken cancellationToken = default);
public Task<bool> UnlockResourceAsync(string resourceId, string lockId, bool force, CancellationToken cancellationToken = default);
private Task<bool> UnlockResourceAsync(string resourceId, string lockId, string resourceType, bool force, CancellationToken cancellationToken = default);
public Task<bool> UnlockResourceAsync(ResourceLock resourceLock, CancellationToken cancellationToken = default);
public Task<bool> UnlockResourceAsync(ResourceLock resourceLock, bool force, CancellationToken cancellationToken = default)
}
```

I will have the raw functions as well.  just didnt prototype them yet.

**Comment by TylerBrinkley** [comment]
If the property we're using for the Id is `Id` then we don't need to add the explicit interface implementation of `IIdentifiable.Id` and don't need the `IdPropertyNameAttribute`.

Could you add namespaces to the proposal?

**Comment by hfcjweinstock** [comment]
updated

**Comment by TylerBrinkley** [comment]
For the namespace I'd say we should try to stick with the api path naming so in this case it would be `EncompassRest.ResourceLocks`. Thoughts?

**Comment by TylerBrinkley** [comment]
That makes sense. We should be free to expand those methods as needed.

**Comment by TylerBrinkley** [comment]
Just an FYI, I reformatted your proposed API.

**Comment by TylerBrinkley** [comment]
I'm thinking `ResourceLock.Resource` should be the `EntityReference` type which is currently in the `EncompassRest.Loans` namespace. I suppose it ought to be moved to the root `EncompassRest` namespace and then used here. We'll want to also move the `EntityType` enum from the `EncompassRest.Loans.Enums` namespace to the root `EncompassRest` namespace as well.

**Comment by hfcjweinstock** [comment]
agree that the enums should all move to the Enum namespace, but we need to be careful because the `EntityReference` is not the same as the `Resource`.  they have different properties available, and the `EntityType` list is different as well.

**Comment by TylerBrinkley** [comment]
I would guess under the covers they're the same type but the properties `EntityName` and `EntityUri` are null and thus aren't serialized back to us.

I wish they would just give us schema endpoints for all the objects we need to access their API's.

**Comment by TylerBrinkley** [comment]
@hfcjweinstock  I updated the proposal some. Could you review my comments by the methods?

**Comment by hfcjweinstock** [comment]
i changed a bunch as i was working on this.
i will update the proposal in a bit.

**Comment by hfcjweinstock** [comment]
updated with my changes and answers

**Comment by TylerBrinkley** [comment]
I've updated the proposal. Main things:

* Moved `EntityReference` and `EntityType` to root `EncompassRest` namespace.
* Added `EntityType.Loan`.
* Changed `ResourceLock.LockTime` to a `DateTime?`.
* Added note regarding overloads that assume a resource type of loan: I don't like that this assumes a resource type of loan. Might as well rename the method then. But if you're going to do that might as well just make a helper method in `LoanApis`.
* I think lockId should be the first parameter as I believe it should be the only required parameter. I made a post in the forums regarding why the other parameters are required at https://forum.elliemae.com/index.php?/topic/6361-resourcelocks-api-question/

**Comment by hfcjweinstock** [comment]
i think `lockId` should be first because that is the resourceID for the lock.  makes more sense from a convention standpoint.

**Comment by hfcjweinstock** [comment]
agreed on the public.  i am going to remove the specific "loan" paths. it will free things up for later development without having to rewrite this.

agreed on the lockTime

**Comment by TylerBrinkley** [comment]
What do you think about adding the following convenience methods?

```diff
 namespace EncompassRest.Loans {
     public class LoanApis : LoanApiObject {
+        public Task<List<ResourceLock>> GetLocksAsync(CancellationToken cancellationToken = default);
+        public Task<ResourceLock> GetLockAsync(string lockId,  CancellationToken cancellationToken = default);
+        public Task<ResourceLock> LockAsync(ResourceLockType lockType, CancellationToken cancellationToken = default);
+        public Task<ResourceLock> LockAsync(ResourceLockType lockType, bool force, CancellationToken cancellationToken = default);
+        public Task<ResourceLock> LockAsync(string lockType, CancellationToken cancellationToken = default);
+        public Task<ResourceLock> LockAsync(string lockType, bool force, CancellationToken cancellationToken = default);
+        public Task<bool> UnlockAsync(string lockId, CancellationToken cancellationToken = default); 
+        public Task<bool> UnlockAsync(string lockId, bool force, CancellationToken cancellationToken = default);
     }
 }
```

**Comment by TylerBrinkley** [comment]
Do you want to hold off on making the `ResourceLocks` type public for now until Ellie Mae makes the resourceId and resourceType not required? We could still add the rest including the `LoanApis` addition.

**Comment by hfcjweinstock** [comment]
that might work for now.

**Comment by TylerBrinkley** [comment]
I've updated the proposal to mostly match the PR.
