### ISSUE TITLE
LiabilityType doesn't match schema

### ISSUE THREAD

**Issue by amadard** [EncompassRest/EncompassRest#88]
The Enum for Liability Type doesn't match the schema.

```c#
namespace EncompassRest.Loans.Enums
{
    public enum LiabilityType
    {
        ChildCare = 0,
        ChildSupport = 1,
        CollectionsJudgementsAndLiens = 2,
        HELOC = 3,
        Installment = 4,
        LeasePayments = 5,
        MortgageLoan = 6,
        Open30DayChargeAccount = 7,
        OtherLiability = 8,
        Revolving = 9,
        SeparateMaintenanceExpense = 10,
        OtherExpense = 11,
        Taxes = 12
    }
}
```

I pulled the schema for field 271 and got the below raw json.
```js
{
	"schema_version": "1.0",
	"entity_types": {
		"Loan": {
			"properties": {
				"CurrentApplication": {
					"entity_type": "Application",
					"nullable": false,
					"required": false,
					"type": "entity"
				},
				"Applications": {
					"element_type": "Application",
					"type": "list"
				}
			}
		},
		"Application": {
			"properties": {
				"Liabilities": {
					"element_type": "Liability",
					"fixed_length": true,
					"instances": {
						"Application_Liabilities_Alimony": {
							"LiabilityType": "Alimony"
						}
					},
					"type": "list"
				}
			}
		},
		"Liability": {
			"properties": {
				"LiabilityType": {
					"nullable": false,
					"allowed_values": [
						**"Undefined",
						"Alimony",
						"JobRelatedExpenses",
						"ChildCare",
						"ChildSupport",
						"CollectionsJudgementsAndLiens",
						"HELOC",
						"Installment",
						"LeasePayments",
						"MortgageLoan",
						"Open30DayChargeAccount",
						"OtherLiability",
						"Revolving",
						"SeparateMaintenanceExpense",
						"OtherExpense",
						"Taxes"**
					],
					"type": "string"
				},
				"Description": {
					"nullable": false,
					"field_instances": {
						"271": [
							"Application_Liabilities_Alimony"
						]
					},
					"description": "Liabilities Alimony/Child Support Descr",
					"type": "string"
				}
			}
		}
	}
}
```

**Comment by hfcjweinstock** [comment]
strange : my allowed values do not have the added options.

"LiabilityType": {
                    "nullable": false,
                    "allowed_values": [
                        {
                            "value": "ChildCare",
                            "text": "Child Care"
                        },
                        {
                            "value": "ChildSupport",
                            "text": "Child Support"
                        },
                        {
                            "value": "CollectionsJudgementsAndLiens",
                            "text": "Collections Judgments And Liens"
                        },
                        {
                            "value": "HELOC",
                            "text": "HELOC"
                        },
                        {
                            "value": "Installment",
                            "text": "Installment"
                        },
                        {
                            "value": "LeasePayments",
                            "text": "Lease Payments"
                        },
                        {
                            "value": "MortgageLoan",
                            "text": "Mortgage"
                        },
                        {
                            "value": "Open30DayChargeAccount",
                            "text": "Open 30 Days Charge Account"
                        },
                        {
                            "value": "OtherLiability",
                            "text": "Other Liability"
                        },
                        {
                            "value": "Revolving",
                            "text": "Revolving"
                        },
                        {
                            "value": "SeparateMaintenanceExpense",
                            "text": "Separate Maintenance Expense"
                        },
                        {
                            "value": "OtherExpense",
                            "text": "Other Expense"
                        },
                        {
                            "value": "Taxes",
                            "text": "Taxes"
                        }
                    ],

**Comment by hfcjweinstock** [comment]
ah.  i see the issue.  if you pull the whole schema, you get the list we have.
if you pull field 271 you get your list.

{
    "schema_version": "1.0",
    "entity_types": {
        "Loan": {
            "properties": {
                "CurrentApplication": {
                    "entity_type": "Application",
                    "nullable": false,
                    "required": false,
                    "type": "entity"
                },
                "Applications": {
                    "element_type": "Application",
                    "type": "list"
                }
            }
        },
        "Application": {
            "properties": {
                "Liabilities": {
                    "element_type": "Liability",
                    "fixed_length": true,
                    "instances": {
                        "Application_Liabilities_Alimony": {
                            "LiabilityType": "Alimony"
                        }
                    },
                    "type": "list"
                }
            }
        },
        "Liability": {
            "properties": {
                "LiabilityType": {
                    "nullable": false,
                    "allowed_values": [
                        "Undefined",
                        "Alimony",
                        "JobRelatedExpenses",
                        "ChildCare",
                        "ChildSupport",
                        "CollectionsJudgementsAndLiens",
                        "HELOC",
                        "Installment",
                        "LeasePayments",
                        "MortgageLoan",
                        "Open30DayChargeAccount",
                        "OtherLiability",
                        "Revolving",
                        "SeparateMaintenanceExpense",
                        "OtherExpense",
                        "Taxes"
                    ],
                    "type": "string"
                },
                "Description": {
                    "nullable": false,
                    "field_instances": {
                        "271": [
                            "Application_Liabilities_Alimony"
                        ]
                    },
                    "description": "Liabilities Alimony/Child Support Descr",
                    "type": "string"
                }
            }
        }
    }
}

**Comment by TylerBrinkley** [comment]
Sounds like an Ellie Mae schema issue.
