### ISSUE TITLE
AssetType doesn't include all options

### ISSUE THREAD

**Issue by amadard** [EncompassRest/EncompassRest#89]
I am not sure how to correct this, but the AssetType matches the schema for AssetType, but leaves out the values for the 1003 assets that have standard field ids, (not multi-instance).

This is the current enum:
```c#
namespace EncompassRest.Loans.Enums
{
    public enum AssetType
    {
        CheckingAccount = 0,
        SavingsAccount = 1,
        MutualFund = 2,
        OtherLiquidAssets = 3,
        PendingNetSaleProceedsFromRealEstateAssets = 4,
        CertificateOfDepositTimeDeposit = 5,
        MoneyMarketFund = 6,
        TrustAccount = 7,
        RetirementFund = 8,
        GiftsTotal = 9,
        GiftsNotDeposited = 10,
        GiftOfEquity = 11,
        BridgeLoanNotDeposited = 12,
        SecuredBorrowedFundsNotDeposited = 13,
        CashDepositOnSalesContract = 14,
        CashOnHand = 15,
        NetWorthOfBusinessOwned = 16,
        OtherNonLiquidAssets = 17,
        NetEquity = 18
    }
}
```

However, it is missing the values for the Field Instances in the Asset Entity:

```js
					"field_instances": {
						"183": [
							"Application_Assets_CashOnHand_NN:1"
						],
						"210": [
							"Application_Assets_LifeInsurance_NN"
						],
						"212": [
							"Application_Assets_OtherNonLiquidAssets_NN:5"
						],
						"213": [
							"Application_Assets_OtherNonLiquidAssets_NN:6"
						],
						"215": [
							"Application_Assets_Automobile_NN:1"
						],
						"217": [
							"Application_Assets_Automobile_NN:2"
						],
						"222": [
							"Application_Assets_OtherNonLiquidAssets_NN:1"
						],
						"224": [
							"Application_Assets_OtherNonLiquidAssets_NN:2"
						],
						"1053": [
							"Application_Assets_OtherNonLiquidAssets_NN:3"
						],
						"1055": [
							"Application_Assets_OtherNonLiquidAssets_NN:4"
						],
						"1605": [
							"Application_Assets_Stock_NN:1"
						],
						"1607": [
							"Application_Assets_Stock_NN:2"
						],
						"1609": [
							"Application_Assets_Stock_NN:3"
						],
						"1716": [
							"Application_Assets_CashOnHand_NN:2"
						],
						"1718": [
							"Application_Assets_Automobile_NN:3"
						]
```

**Comment by hfcjweinstock** [comment]
for the field specific options, if you look up the field you will find the assetType to lookup to find that value : 
Loan.Application[0].Asset["CashOnHand"].CashOrMarketValueAmount is field 183.

it does appear we are missing LifeInsurance From the AssetTypes.

**Comment by amadard** [comment]
Here is how I am currently coding how I add to the list, is this not the recommended setup?

            restApp.Assets.Add(new restLoans.Asset()
            {
                AssetType = "CashOnHand",
                AccountIdentifier = ""NAME",
                CashOrMarketValueAmount = decimal.Parse("AMOUNT"),
                AssetIndex = 1
            });

**Comment by hfcjweinstock** [comment]
that should work....althought  im not sure about the index.  the best bet is to pull a loan that has it and see how it is formatted.

**Comment by hfcjweinstock** [comment]
this also may be an issue with the EM side of things.  multi value fields may not work correctly yet.  not sure.
