### ISSUE TITLE
Error with Deserializing Loan object

### ISSUE THREAD

**Issue by amadard** [EncompassRest/EncompassRest#97]
I have an object that includes a EncompassRest.Loans.Loan object as a property.  The property is null and I serialize the object.  Everything works just fine.

I then go to deserialize the object, and I get this error from JSON.NET (JsonConvert.DeserializeObject<>(string)

Additional text found in JSON string after finishing deserializing object.

After confirming it was the Loan property causing it, I changed the loan property to an Object, and everything worked fine. 

Not sure if this is something that can be corrected.

**Comment by TylerBrinkley** [comment]
Could you please provide more details or a minimal reproduction.

**Comment by amadard** [comment]
This code triggers the error for me:

        private void TestError()
        {
            try
            {
                TestObject testObject = new TestObject();
                testObject.TestString = "TESTING";

                string testString = Newtonsoft.Json.JsonConvert.SerializeObject(testObject);

                TestObject newObject = Newtonsoft.Json.JsonConvert.DeserializeObject<TestObject>(testString);
            }
            catch (Exception ex)
            {
                string error = ex.Message;
            }
        }

        public class TestObject
        {
            public EncompassRest.Loans.Loan loanObject { get; set; }
            public string TestString { get; set; }
        }

**Comment by hfcjweinstock** [comment]
we are missing a public create from serialized.

**Comment by TylerBrinkley** [comment]
That's what the `JsonConstructorAttribute` is for. It should work fine.

**Comment by hfcjweinstock** [comment]
ok.  not sure why this is happening, but
```c#
    public class TestObject
    {
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public EncompassRest.Loans.Loan loanObject { get; set; }
        public string TestString { get; set; }
    }
```
will work.

**Comment by TylerBrinkley** [comment]
I figured out the issue and will post a fix tonight.
