### ISSUE TITLE
CreateLoanRawAsync Error - Loan Processing Failed

### ISSUE THREAD

**Issue by amadard** [EncompassRest/EncompassRest#99]
I have checked my system, and I don't find anything that would indicate it is a business rule causing the issue, and I am using a SuperAdmin account licensed in all states to create the loan.

I am getting Loan Processing Failed whenever I try to create a loan that has property.State, or propertyEstimatedValueAmount populated.  I have tried on multiple accounts and keep getting the error.  I can't find anything that would explain why, which is why I am reaching out to find out if it is possibly the API, or if you know about this at all.

{"summary":"Conflict","details":"Loan processing failed"}

            string json = "{	\"property\": {		\"state\": \"CA\",	},	\"propertyEstimatedValueAmount\": 750000,}";

            string value1 = Task.Run(async () =>
            {
                using (var client = await EncompassRestClient.CreateFromUserCredentialsAsync(_ClientID, _ClientSecret, _InstanceID, _UserID, _UserPassword))
                {
                    return await client.Loans.CreateLoanRawAsync(json);
                }

            }).GetAwaiter().GetResult();

**Comment by TylerBrinkley** [comment]
Have you tried the same with Postman?

**Comment by amadard** [comment]
Will do!

**Comment by amadard** [comment]
Yes, get the error in PostMan as well.

**Comment by hfcjweinstock** [comment]
you have erroneous commas.
try
``` c#
 string json = "{	\"property\": {		\"state\": \"CA\"	},	\"propertyEstimatedValueAmount\": 750000}";
```

**Comment by amadard** [comment]
Still fails.  I fixed those for PostMan, it didn't succeed either.

Have you seen this before?  Does this look like an API thing, or something related to my system?

**Comment by amadard** [comment]
Using a workaround, clearly not an issue with EncompassRest.

Will take it up with Ellie Mae to resolve.
